/*
 * ���� com.yougou.kaidian.order.model.MerchantActiveCommodityQuery
 * 
 * ����  Tue Oct 13 09:44:01 CST 2015
 * 
 * ��Ȩ����Copyright (C) 2013 YouGou Information Technology Co.,Ltd 
 * All Rights Reserved. 
 * 
 * The software for the YouGou technology development, without the 
 * company's written consent, and any other individuals and 
 * organizations shall not be used, Copying, Modify or distribute 
 * the software.
 * 
 */
package com.yougou.kaidian.active.vo;

import java.math.BigDecimal;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.apache.commons.lang.StringUtils;

public class MerchantActiveCommodityQuery {
    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_active_commodity
     *
     * @yougougenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_active_commodity
     *
     * @yougougenerated
     */
    protected String oderProperty;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_active_commodity
     *
     * @yougougenerated
     */
    protected String oderType;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_active_commodity
     *
     * @yougougenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_active_commodity
     *
     * @yougougenerated
     */
    protected List<Criteria> oredCriteria;

    public MerchantActiveCommodityQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        if (StringUtils.isEmpty(orderByClause) && StringUtils.isNotEmpty(this.getOderProperty()) && StringUtils.isNotEmpty(this.getOderType())){
            return MessageFormat.format("{0} {1}", this.getOderProperty(),this.getOderType());
        }
        return orderByClause;
    }

    public void setOderProperty(String oderProperty) {
        this.oderProperty = oderProperty;
    }

    public String getOderProperty() {
        return oderProperty;
    }

    public void setOderType(String oderType) {
        this.oderType = oderType;
    }

    public String getOderType() {
        return oderType;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_merchant_active_commodity
     *
     * @yougougenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public Criteria setLimitValue(int value1, int value2) {
            if (value2 == 0 )
              throw new RuntimeException("value2 is 0");
            addCriterion("limit",value1,value2,"null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value, property));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSignupIdIsNull() {
            addCriterion("signup_id is null");
            return (Criteria) this;
        }

        public Criteria andSignupIdIsNotNull() {
            addCriterion("signup_id is not null");
            return (Criteria) this;
        }

        public Criteria andSignupIdEqualTo(String value) {
            addCriterion("signup_id =", value, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdNotEqualTo(String value) {
            addCriterion("signup_id <>", value, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdGreaterThan(String value) {
            addCriterion("signup_id >", value, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdGreaterThanOrEqualTo(String value) {
            addCriterion("signup_id >=", value, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdLessThan(String value) {
            addCriterion("signup_id <", value, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdLessThanOrEqualTo(String value) {
            addCriterion("signup_id <=", value, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdLike(String value) {
            addCriterion("signup_id like", value, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdNotLike(String value) {
            addCriterion("signup_id not like", value, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdIn(List<String> values) {
            addCriterion("signup_id in", values, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdNotIn(List<String> values) {
            addCriterion("signup_id not in", values, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdBetween(String value1, String value2) {
            addCriterion("signup_id between", value1, value2, "signupId");
            return (Criteria) this;
        }

        public Criteria andSignupIdNotBetween(String value1, String value2) {
            addCriterion("signup_id not between", value1, value2, "signupId");
            return (Criteria) this;
        }      

        public Criteria andComodityNoIsNull() {
            addCriterion("comodity_no is null");
            return (Criteria) this;
        }

        public Criteria andComodityNoIsNotNull() {
            addCriterion("comodity_no is not null");
            return (Criteria) this;
        }

        public Criteria andComodityNoEqualTo(String value) {
            addCriterion("comodity_no =", value, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoNotEqualTo(String value) {
            addCriterion("comodity_no <>", value, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoGreaterThan(String value) {
            addCriterion("comodity_no >", value, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoGreaterThanOrEqualTo(String value) {
            addCriterion("comodity_no >=", value, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoLessThan(String value) {
            addCriterion("comodity_no <", value, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoLessThanOrEqualTo(String value) {
            addCriterion("comodity_no <=", value, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoLike(String value) {
            addCriterion("comodity_no like", value, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoNotLike(String value) {
            addCriterion("comodity_no not like", value, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoIn(List<String> values) {
            addCriterion("comodity_no in", values, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoNotIn(List<String> values) {
            addCriterion("comodity_no not in", values, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoBetween(String value1, String value2) {
            addCriterion("comodity_no between", value1, value2, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andComodityNoNotBetween(String value1, String value2) {
            addCriterion("comodity_no not between", value1, value2, "comodityNo");
            return (Criteria) this;
        }

        public Criteria andActivePriceIsNull() {
            addCriterion("active_price is null");
            return (Criteria) this;
        }

        public Criteria andActivePriceIsNotNull() {
            addCriterion("active_price is not null");
            return (Criteria) this;
        }

        public Criteria andActivePriceEqualTo(BigDecimal value) {
            addCriterion("active_price =", value, "activePrice");
            return (Criteria) this;
        }

        public Criteria andActivePriceNotEqualTo(BigDecimal value) {
            addCriterion("active_price <>", value, "activePrice");
            return (Criteria) this;
        }

        public Criteria andActivePriceGreaterThan(BigDecimal value) {
            addCriterion("active_price >", value, "activePrice");
            return (Criteria) this;
        }

        public Criteria andActivePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("active_price >=", value, "activePrice");
            return (Criteria) this;
        }

        public Criteria andActivePriceLessThan(BigDecimal value) {
            addCriterion("active_price <", value, "activePrice");
            return (Criteria) this;
        }

        public Criteria andActivePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("active_price <=", value, "activePrice");
            return (Criteria) this;
        }

        public Criteria andActivePriceIn(List<BigDecimal> values) {
            addCriterion("active_price in", values, "activePrice");
            return (Criteria) this;
        }

        public Criteria andActivePriceNotIn(List<BigDecimal> values) {
            addCriterion("active_price not in", values, "activePrice");
            return (Criteria) this;
        }

        public Criteria andActivePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("active_price between", value1, value2, "activePrice");
            return (Criteria) this;
        }

        public Criteria andActivePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("active_price not between", value1, value2, "activePrice");
            return (Criteria) this;
        }

        public Criteria andCouponAmountIsNull() {
            addCriterion("coupon_amount is null");
            return (Criteria) this;
        }

        public Criteria andCouponAmountIsNotNull() {
            addCriterion("coupon_amount is not null");
            return (Criteria) this;
        }

        public Criteria andCouponAmountEqualTo(BigDecimal value) {
            addCriterion("coupon_amount =", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountNotEqualTo(BigDecimal value) {
            addCriterion("coupon_amount <>", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountGreaterThan(BigDecimal value) {
            addCriterion("coupon_amount >", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("coupon_amount >=", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountLessThan(BigDecimal value) {
            addCriterion("coupon_amount <", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("coupon_amount <=", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountIn(List<BigDecimal> values) {
            addCriterion("coupon_amount in", values, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountNotIn(List<BigDecimal> values) {
            addCriterion("coupon_amount not in", values, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("coupon_amount between", value1, value2, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("coupon_amount not between", value1, value2, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_merchant_active_commodity
     *
     * @yougougenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_merchant_active_commodity
     *
     * @yougougenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
              this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}