package com.belle.other.model.pojo;

// Generated 2011-5-24 10:21:51 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import com.belle.yitiansystem.merchant.constant.MerchantConstant;
import com.yougou.merchant.api.supplier.vo.BrandVo;

/**
 * TblSupplier generated by hbm2java
 */
@Entity
@Table(name = "tbl_sp_supplier")
public class SupplierSp implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String id;
	private String supplierCode;//供应商编码
	private String supplier;//供应商名称
	private String englishName;//供应商英文名
	private String simpleName;//供应商简写
	private String contact;//开户人
	private String telePhone;//电话
	private String email;//电子邮件
	private String fax;//传真
	private String address;//地址
	private String url;//网址
	private String remark;//备注
	private Integer isValid = MerchantConstant.MERCHANT_STATUS_ENABLE;//状态 
	private String supplierType;//供应商类型
	private String bank;//开户行
	private String subBank;//支行
	private String dutyCode;// 税号
	private String creator;//创建人
	private String account;//账户
	private String payType;//支付方式
	private Integer conTime;//合作期限
	private String loginAccount;//登录名
	private String loginPassword;//登录密码
	private Integer isConfig;//是否用做供应商商品管理 1适用 0 或 null不适用
	private Integer isUseYougouWms;//是否使用优购WMS 默认否0 是1
		
	private Date updateDate;  //修改时间
	
	private String updateUser;  //修改人
	
	private Double taxRate;	  //税率	
	
	private Double couponsAllocationProportion;  //优惠券分摊比例

	//招商系统增加字段  wang.m   2012-03-05
	private String businessLicense;//营业执照号
	private String businessLocal;//营业执照所在地
	private String businessValidity;//营业执照有效期
	private String tallageNo;//纳税人识别号
	private String institutional;//组织机构代码
	private String taxpayer;//一般纳税人
	private String bankLocal;//开户行银行所在地
    
	private String inventoryCode;//仓库名称
	
	/**
	 * 是否入优购仓库
	 * 1 入优购仓库，优购发货（默认项）
	 * 0 不入优购仓库，商家发货
	 * 2 不入优购仓库，优购发货
	 */
	private Integer isInputYougouWarehouse;

    private String setOfBooksCode;// 成本帐套编号
	
	private String setOfBooksName;//成本账套名称
	
	private String balanceTraderCode;//结算商家编码
	
	private String balanceTraderName;//结算商家名字balance_trader_name
	
	private String posSourceNo;//pos供应商编码
	
	private Integer deleteFlag;//删除标志 0表示已删除  1表示未删除
	
	private Integer shipmentType;//按发货预结算 1：按发货预结算；0：不按发货预结算；
	
	private String tradeCurrency;//结算币种

	private List<BrandVo> brandVos;

	private Set<SupplierUpdateHistory> supplierUpdateHistories = new HashSet<SupplierUpdateHistory>();
	

	/**
     * 时间戳
     */
    private Long updateTimestamp;
	private Set<SupplierContactSp> supplierContact=new HashSet<SupplierContactSp>();
	
	@Column(name = "business_license", length = 100)
	public String getBusinessLicense() {
		return businessLicense;
	}

	public void setBusinessLicense(String businessLicense) {
		this.businessLicense = businessLicense;
	}
	@Column(name = "business_local", length = 50)
	public String getBusinessLocal() {
		return businessLocal;
	}
	public void setBusinessLocal(String businessLocal) {
		this.businessLocal = businessLocal;
	}
	@Column(name = "business_vilidity", length = 100)
	public String getBusinessValidity() {
		return businessValidity;
	}

	public void setBusinessValidity(String businessValidity) {
		this.businessValidity = businessValidity;
	}
	@Column(name = "tallage_no", length = 100)
	public String getTallageNo() {
		return tallageNo;
	}

	public void setTallageNo(String tallageNo) {
		this.tallageNo = tallageNo;
	}
	@Column(name = "institutional", length = 50)
	public String getInstitutional() {
		return institutional;
	}

	public void setInstitutional(String institutional) {
		this.institutional = institutional;
	}
	@Column(name = "taxpayer", length = 50)
	public String getTaxpayer() {
		return taxpayer;
	}

	public void setTaxpayer(String taxpayer) {
		this.taxpayer = taxpayer;
	}
	@Column(name = "bank_local", length = 100)
	public String getBankLocal() {
		return bankLocal;
	}

	public void setBankLocal(String bankLocal) {
		this.bankLocal = bankLocal;
	}
	@Column(name = "inventory_code", length = 50)
	public String getInventoryCode() {
		return inventoryCode;
	}

	public void setInventoryCode(String inventoryCode) {
		this.inventoryCode = inventoryCode;
	}
	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public SupplierSp() {
	}

	public SupplierSp(String id) {
		this.id = id;
	}

	public SupplierSp(String id, String supplierCode, String supplier,
			String englishName, String simpleName, String contact,
			String telePhone, String email, String fax, String address,
			String url, String remark, Integer isValid, String supplierType,
			String bank, String subBank, String dutyCode, String creator,
			String account, String payType, Integer conTime,Long updateTimestamp,
			String loginAccount, String loginPassword) {
		this.id = id;
		this.supplierCode = supplierCode;
		this.supplier = supplier;
		this.englishName = englishName;
		this.simpleName = simpleName;
		this.contact = contact;
		this.telePhone = telePhone;
		this.email = email;
		this.fax = fax;
		this.updateTimestamp = updateTimestamp;
		this.address = address;
		this.url = url;
		this.remark = remark;
		this.isValid = isValid;
		this.supplierType = supplierType;
		this.bank = bank;
		this.subBank = subBank;
		this.dutyCode = dutyCode;
		this.creator = creator;
		this.account = account;
		this.payType = payType;
		this.conTime = conTime;
		this.loginAccount = loginAccount;
		this.loginPassword = loginPassword;
	}

	public SupplierSp(String id, String supplierCode, String supplier,
			String englishName, String simpleName, String contact,
			String telePhone, String email, String fax, String address,
			String url, String remark, Integer isValid, String supplierType,
			String bank, String subBank, String dutyCode, String creator,
			String account, String payType, Integer conTime,
			Long updateTimestamp, Date updateDate, String inventoryCode,
			Integer isInputYougouWarehouse, Double couponsAllocationProportion,
			String updateUser) {
		this.id = id;
		this.supplierCode = supplierCode;
		this.supplier = supplier;
		this.englishName = englishName;
		this.simpleName = simpleName;
		this.contact = contact;
		this.telePhone = telePhone;
		this.email = email;
		this.fax = fax;
		this.updateTimestamp = updateTimestamp;
		this.address = address;
		this.url = url;
		this.remark = remark;
		this.isValid = isValid;
		this.supplierType = supplierType;
		this.bank = bank;
		this.subBank = subBank;
		this.dutyCode = dutyCode;
		this.creator = creator;
		this.account = account;
		this.payType = payType;
		this.conTime = conTime;
		this.updateDate = updateDate;
		this.inventoryCode = inventoryCode;
		this.isInputYougouWarehouse = isInputYougouWarehouse;
		this.couponsAllocationProportion = couponsAllocationProportion;
		this.updateUser = updateUser;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "supplier_code", length = 32)
	public String getSupplierCode() {
		return this.supplierCode;
	}

	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	@Column(name = "supplier", length = 100)
	public String getSupplier() {
		return this.supplier;
	}

	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	@Column(name = "english_name", length = 100)
	public String getEnglishName() {
		return this.englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	@Column(name = "simple_name", length = 100)
	public String getSimpleName() {
		return this.simpleName;
	}

	public void setSimpleName(String simpleName) {
		this.simpleName = simpleName;
	}

	@Column(name = "contact", length = 32)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "tele_phone", length = 32)
	public String getTelePhone() {
		return this.telePhone;
	}

	public void setTelePhone(String telePhone) {
		this.telePhone = telePhone;
	}

	@Column(name = "email", length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fax", length = 32)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "address", length = 64)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "url", length = 32)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "is_valid")
	public Integer getIsValid() {
		return this.isValid;
	}

	public void setIsValid(Integer isValid) {
		this.isValid = isValid;
	}

	@Column(name = "supplier_type", length = 32)
	public String getSupplierType() {
		return this.supplierType;
	}

	public void setSupplierType(String supplierType) {
		this.supplierType = supplierType;
	}

	@Column(name = "bank", length = 32)
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	@Column(name = "sub_bank", length = 32)
	public String getSubBank() {
		return this.subBank;
	}

	public void setSubBank(String subBank) {
		this.subBank = subBank;
	}

	@Column(name = "duty_code", length = 32)
	public String getDutyCode() {
		return this.dutyCode;
	}

	public void setDutyCode(String dutyCode) {
		this.dutyCode = dutyCode;
	}

	@Column(name = "creator", length = 32)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "account", length = 32)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "pay_type", length = 32)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "con_time")
	public Integer getConTime() {
		return this.conTime;
	}

	public void setConTime(Integer conTime) {
		this.conTime = conTime;
	}

	@Column(name = "login_account", length = 32)
	public String getLoginAccount() {
		return this.loginAccount;
	}

	public void setLoginAccount(String loginAccount) {
		this.loginAccount = loginAccount;
	}

	@Column(name = "login_password", length = 32)
	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}
	
	@Column(name = "is_config")
	public Integer getIsConfig() {
		return isConfig;
	}

	public void setIsConfig(Integer isConfig) {
		this.isConfig = isConfig;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<SupplierContactSp> getSupplierContact() {
		return supplierContact;
	}
	
	public void setSupplierContact(Set<SupplierContactSp> supplierContact) {
		this.supplierContact = supplierContact;
	}
	
    @Column(name="update_timestamp")
	public Long getUpdateTimestamp() {
		return updateTimestamp;
	}

	public void setUpdateTimestamp(Long updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<SupplierUpdateHistory> getSupplierUpdateHistories() {
		return supplierUpdateHistories;
	}

	public void setSupplierUpdateHistories(
			Set<SupplierUpdateHistory> supplierUpdateHistories) {
		this.supplierUpdateHistories = supplierUpdateHistories;
	}

	@Column(name = "update_date", length = 25)
	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	@Column(name = "update_user", length = 50)
	public String getUpdateUser() {
		return updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
	@Column(name = "tax_rate")
	public Double getTaxRate() {
		return taxRate;
	}

	public void setTaxRate(Double taxRate) {
		this.taxRate = taxRate;
	}
	@Column(name = "coupons_allocation_proportion")
	public Double getCouponsAllocationProportion() {
		return couponsAllocationProportion;
	}

	public void setCouponsAllocationProportion(Double couponsAllocationProportion) {
		this.couponsAllocationProportion = couponsAllocationProportion;
	}
	@Column(name = "is_input_yougou_warehouse")
	public Integer getIsInputYougouWarehouse() {
		return isInputYougouWarehouse;
	}

	public void setIsInputYougouWarehouse(Integer isInputYougouWarehouse) {
		this.isInputYougouWarehouse = isInputYougouWarehouse;
	}
	@Column(name = "set_of_books_code")
	public String getSetOfBooksCode() {
		return setOfBooksCode;
	}

	public void setSetOfBooksCode(String setOfBooksCode) {
		this.setOfBooksCode = setOfBooksCode;
	}
	
	@Column(name = "set_of_books_name")
	public String getSetOfBooksName() {
		return setOfBooksName;
	}

	public void setSetOfBooksName(String setOfBooksName) {
		this.setOfBooksName = setOfBooksName;
	}
	
	@Column(name = "balance_trader_code")
	public String getBalanceTraderCode() {
		return balanceTraderCode;
	}

	public void setBalanceTraderCode(String balanceTraderCode) {
		this.balanceTraderCode = balanceTraderCode;
	}
	@Column(name = "balance_trader_name")
	public String getBalanceTraderName() {
		return balanceTraderName;
	}

	public void setBalanceTraderName(String balanceTraderName) {
		this.balanceTraderName = balanceTraderName;
	}
	@Column(name = "pos_source_no")
	public String getPosSourceNo() {
		return posSourceNo;
	}

	public void setPosSourceNo(String posSourceNo) {
		this.posSourceNo = posSourceNo;
	}
	@Column(name = "delete_flag", length = 11)
	public Integer getDeleteFlag() {
		return deleteFlag;
	}

	public void setDeleteFlag(Integer deleteFlag) {
		this.deleteFlag = deleteFlag;
	}
	
	@Column(name = "shipment_type", length = 11)
	public Integer getShipmentType() {
		return shipmentType;
	}

	public void setShipmentType(Integer shipmentType) {
		this.shipmentType = shipmentType;
	}
	
	@Column(name = "trade_currency", length = 50)
	public String getTradeCurrency() {
		return tradeCurrency;
	}

	public void setTradeCurrency(String tradeCurrency) {
		this.tradeCurrency = tradeCurrency;
	}
	
	@Column(name = "is_use_yougou_wms")
	public Integer getIsUseYougouWms() {
		return isUseYougouWms;
	}

	public void setIsUseYougouWms(Integer isUseYougouWms) {
		this.isUseYougouWms = isUseYougouWms;
	}


	@Transient
	public List<BrandVo> getBrandVos() {
		return brandVos;
	}

	public void setBrandVos(List<BrandVo> brandVos) {
		this.brandVos = brandVos;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * 合作模式
	 */
	public static enum CooperationModel {
		/*
		 * 提示：严禁调整枚举常量的先后顺序(因数据库记录的是枚举常量的顺序值)
		 */
		NON_ENTER_YOUGOU_WAREHOUSE_MERCHANT_DELIVERY("不入优购仓库，商家发货", true),
		ENTER_YOUGOU_WAREHOUSE_YOUGOU_DELIVERY("入优购仓库，优购发货"),
		NON_ENTER_YOUGOU_WAREHOUSE_YOUGOU_DELIVERY("不入优购仓库，优购发货");
		
		private String description;
		private boolean checked;

		private CooperationModel(String description) {
			this(description, false);
		}

		private CooperationModel(String description, boolean checked) {
			this.description = description;
			this.checked = checked;
		}
		
		public String getDescription() {
			return description;
		}

		public boolean isChecked() {
			return checked;
		}
	}

	
}
