package com.belle.other.model.pojo;

// Generated 2011-5-24 10:21:51 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TblSupplierContact generated by hbm2java
 */
@Entity
@Table(name = "tbl_sp_supplier_contact")
public class SupplierContactSp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private SupplierSp supplier;//供应商
	private Integer type;//类型
	private String contact;//内容
	private String telePhone;//电话
	private String mobilePhone;//手机
	private String email;//邮箱
	private String fax;//传真
	private String address;//详细地址

	public SupplierContactSp() {
	}

	public SupplierContactSp(String id) {
		this.id = id;
	}

	public SupplierContactSp(String id, SupplierSp supplier, Integer type,
			String contact, String telePhone, String mobilePhone, String email,
			String fax, String address) {
		this.id = id;
		this.supplier = supplier;
		this.type = type;
		this.contact = contact;
		this.telePhone = telePhone;
		this.mobilePhone = mobilePhone;
		this.email = email;
		this.fax = fax;
		this.address = address;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="supply_id")
	public SupplierSp getSupplier() {
		return this.supplier;
	}
	
	public void setSupplier(SupplierSp supplier) {
		this.supplier = supplier;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "contact", length = 32)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "tele_phone", length = 32)
	public String getTelePhone() {
		return this.telePhone;
	}

	public void setTelePhone(String telePhone) {
		this.telePhone = telePhone;
	}

	@Column(name = "mobile_phone", length = 32)
	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@Column(name = "email", length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fax", length = 32)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "address", length = 64)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
