/*
 * 类名 com.yougou.kaidian.order.model.MerchantOrderExpandQuery
 * 
 * 日期  Tue Sep 22 13:49:39 CST 2015
 * 
 * 版权声明Copyright (C) 2013 YouGou Information Technology Co.,Ltd 
 * All Rights Reserved. 
 * 
 * The software for the YouGou technology development, without the 
 * company's written consent, and any other individuals and 
 * organizations shall not be used, Copying, Modify or distribute 
 * the software.
 * 
 */
package com.yougou.kaidian.order.model;

import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.apache.commons.lang.StringUtils;

public class MerchantOrderExpandQuery {
    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_order_expand
     *
     * @yougougenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_order_expand
     *
     * @yougougenerated
     */
    protected String oderProperty;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_order_expand
     *
     * @yougougenerated
     */
    protected String oderType;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_order_expand
     *
     * @yougougenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by YouGou MyBatis Generator.
     * This field corresponds to the database table tbl_merchant_order_expand
     *
     * @yougougenerated
     */
    protected List<Criteria> oredCriteria;

    public MerchantOrderExpandQuery() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        if (StringUtils.isEmpty(orderByClause) && StringUtils.isNotEmpty(this.getOderProperty()) && StringUtils.isNotEmpty(this.getOderType())){
            return MessageFormat.format("{0} {1}", this.getOderProperty(),this.getOderType());
        }
        return orderByClause;
    }

    public void setOderProperty(String oderProperty) {
        this.oderProperty = oderProperty;
    }

    public String getOderProperty() {
        return oderProperty;
    }

    public void setOderType(String oderType) {
        this.oderType = oderType;
    }

    public String getOderType() {
        return oderType;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_merchant_order_expand
     *
     * @yougougenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public Criteria setLimitValue(int value1, int value2) {
            if (value2 == 0 )
              throw new RuntimeException("value2 is 0");
            addCriterion("limit",value1,value2,"null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value, property));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdIsNull() {
            addCriterion("order_sub_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdIsNotNull() {
            addCriterion("order_sub_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdEqualTo(String value) {
            addCriterion("order_sub_id =", value, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdNotEqualTo(String value) {
            addCriterion("order_sub_id <>", value, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdGreaterThan(String value) {
            addCriterion("order_sub_id >", value, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_sub_id >=", value, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdLessThan(String value) {
            addCriterion("order_sub_id <", value, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdLessThanOrEqualTo(String value) {
            addCriterion("order_sub_id <=", value, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdLike(String value) {
            addCriterion("order_sub_id like", value, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdNotLike(String value) {
            addCriterion("order_sub_id not like", value, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdIn(List<String> values) {
            addCriterion("order_sub_id in", values, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdNotIn(List<String> values) {
            addCriterion("order_sub_id not in", values, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdBetween(String value1, String value2) {
            addCriterion("order_sub_id between", value1, value2, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andOrderSubIdNotBetween(String value1, String value2) {
            addCriterion("order_sub_id not between", value1, value2, "orderSubId");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIsNull() {
            addCriterion("merchant_code is null");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIsNotNull() {
            addCriterion("merchant_code is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeEqualTo(String value) {
            addCriterion("merchant_code =", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotEqualTo(String value) {
            addCriterion("merchant_code <>", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeGreaterThan(String value) {
            addCriterion("merchant_code >", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_code >=", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLessThan(String value) {
            addCriterion("merchant_code <", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLessThanOrEqualTo(String value) {
            addCriterion("merchant_code <=", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeLike(String value) {
            addCriterion("merchant_code like", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotLike(String value) {
            addCriterion("merchant_code not like", value, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeIn(List<String> values) {
            addCriterion("merchant_code in", values, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotIn(List<String> values) {
            addCriterion("merchant_code not in", values, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeBetween(String value1, String value2) {
            addCriterion("merchant_code between", value1, value2, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andMerchantCodeNotBetween(String value1, String value2) {
            addCriterion("merchant_code not between", value1, value2, "merchantCode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andMarkColorIsNull() {
            addCriterion("mark_color is null");
            return (Criteria) this;
        }

        public Criteria andMarkColorIsNotNull() {
            addCriterion("mark_color is not null");
            return (Criteria) this;
        }

        public Criteria andMarkColorEqualTo(String value) {
            addCriterion("mark_color =", value, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorNotEqualTo(String value) {
            addCriterion("mark_color <>", value, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorGreaterThan(String value) {
            addCriterion("mark_color >", value, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorGreaterThanOrEqualTo(String value) {
            addCriterion("mark_color >=", value, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorLessThan(String value) {
            addCriterion("mark_color <", value, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorLessThanOrEqualTo(String value) {
            addCriterion("mark_color <=", value, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorLike(String value) {
            addCriterion("mark_color like", value, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorNotLike(String value) {
            addCriterion("mark_color not like", value, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorIn(List<String> values) {
            addCriterion("mark_color in", values, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorNotIn(List<String> values) {
            addCriterion("mark_color not in", values, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorBetween(String value1, String value2) {
            addCriterion("mark_color between", value1, value2, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkColorNotBetween(String value1, String value2) {
            addCriterion("mark_color not between", value1, value2, "markColor");
            return (Criteria) this;
        }

        public Criteria andMarkNoteIsNull() {
            addCriterion("mark_note is null");
            return (Criteria) this;
        }

        public Criteria andMarkNoteIsNotNull() {
            addCriterion("mark_note is not null");
            return (Criteria) this;
        }

        public Criteria andMarkNoteEqualTo(String value) {
            addCriterion("mark_note =", value, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteNotEqualTo(String value) {
            addCriterion("mark_note <>", value, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteGreaterThan(String value) {
            addCriterion("mark_note >", value, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteGreaterThanOrEqualTo(String value) {
            addCriterion("mark_note >=", value, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteLessThan(String value) {
            addCriterion("mark_note <", value, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteLessThanOrEqualTo(String value) {
            addCriterion("mark_note <=", value, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteLike(String value) {
            addCriterion("mark_note like", value, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteNotLike(String value) {
            addCriterion("mark_note not like", value, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteIn(List<String> values) {
            addCriterion("mark_note in", values, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteNotIn(List<String> values) {
            addCriterion("mark_note not in", values, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteBetween(String value1, String value2) {
            addCriterion("mark_note between", value1, value2, "markNote");
            return (Criteria) this;
        }

        public Criteria andMarkNoteNotBetween(String value1, String value2) {
            addCriterion("mark_note not between", value1, value2, "markNote");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_merchant_order_expand
     *
     * @yougougenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by YouGou MyBatis Generator.
     * This class corresponds to the database table tbl_merchant_order_expand
     *
     * @yougougenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
              this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}