package com.yougou.kaidian.order.model;

import java.io.Serializable;
import java.util.Date;

/**
 * @author daixiaowei
 * @date 2012-03-07 10:53:36
 */
public class OrderMain implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_order_main.id
     * 
     * @mbggenerated
     */
    private String  id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.order_main_no
     * 
     * @mbggenerated
     */
    private String  orderMainNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.member_name
     * 
     * @mbggenerated
     */
    private String  memberName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.member_no
     * 
     * @mbggenerated
     */
    private String  memberNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.prod_total_num
     * 
     * @mbggenerated
     */
    private Integer prodTotalNum;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.prod_total_amt
     * 
     * @mbggenerated
     */
    private Double  prodTotalAmt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.payment
     * 
     * @mbggenerated
     */
    private String  payment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.create_time
     * 
     * @mbggenerated
     */
    private Date    createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.reserve_time
     * 
     * @mbggenerated
     */
    private Date    reserveTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.total_giving_scores
     * 
     * @mbggenerated
     */
    private Integer totalGivingScores;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.promotional_programs
     * 
     * @mbggenerated
     */
    private String  promotionalPrograms;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.total_preferential_amount
     * 
     * @mbggenerated
     */
    private Double  totalPreferentialAmount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.order_message
     * 
     * @mbggenerated
     */
    private String  orderMessage;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.del_flag
     * 
     * @mbggenerated
     */
    private Short   delFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.split_flag
     * 
     * @mbggenerated
     */
    private Short   splitFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.order_flag
     * 
     * @mbggenerated
     */
    private Integer orderFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.union_type
     * 
     * @mbggenerated
     */
    private Integer unionType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.lock_user
     * 
     * @mbggenerated
     */
    private String  lockUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.pay_status
     * 
     * @mbggenerated
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.buy_id
     * 
     * @mbggenerated
     */
    private String  buyId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.coupons_no
     * 
     * @mbggenerated
     */
    private String  couponsNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.consignee_id
     * 
     * @mbggenerated
     */
    private String  consigneeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.online_pay_amount
     * 
     * @mbggenerated
     */
    private Double  onlinePayAmount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.client_sign
     * 
     * @mbggenerated
     */
    private String  clientSign;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.order_total_amt
     * 
     * @mbggenerated
     */
    private Double  orderTotalAmt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.should_postage
     * 
     * @mbggenerated
     */
    private Double  shouldPostage;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.actual_postage
     * 
     * @mbggenerated
     */
    private Double  actualPostage;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_main.is_postage_free
     * 
     * @mbggenerated
     */
    private Integer isPostageFree;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.id
     * 
     * @return the value of tbl_order_main.id
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.id
     * 
     * @param id the value for tbl_order_main.id
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.order_main_no
     * 
     * @return the value of tbl_order_main.order_main_no
     * @mbggenerated
     */
    public String getOrderMainNo() {
        return orderMainNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.order_main_no
     * 
     * @param orderMainNo the value for tbl_order_main.order_main_no
     * @mbggenerated
     */
    public void setOrderMainNo(String orderMainNo) {
        this.orderMainNo = orderMainNo == null ? null : orderMainNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.member_name
     * 
     * @return the value of tbl_order_main.member_name
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.member_name
     * 
     * @param memberName the value for tbl_order_main.member_name
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.member_no
     * 
     * @return the value of tbl_order_main.member_no
     * @mbggenerated
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.member_no
     * 
     * @param memberNo the value for tbl_order_main.member_no
     * @mbggenerated
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.prod_total_num
     * 
     * @return the value of tbl_order_main.prod_total_num
     * @mbggenerated
     */
    public Integer getProdTotalNum() {
        return prodTotalNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.prod_total_num
     * 
     * @param prodTotalNum the value for tbl_order_main.prod_total_num
     * @mbggenerated
     */
    public void setProdTotalNum(Integer prodTotalNum) {
        this.prodTotalNum = prodTotalNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.prod_total_amt
     * 
     * @return the value of tbl_order_main.prod_total_amt
     * @mbggenerated
     */
    public Double getProdTotalAmt() {
        return prodTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.prod_total_amt
     * 
     * @param prodTotalAmt the value for tbl_order_main.prod_total_amt
     * @mbggenerated
     */
    public void setProdTotalAmt(Double prodTotalAmt) {
        this.prodTotalAmt = prodTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.payment
     * 
     * @return the value of tbl_order_main.payment
     * @mbggenerated
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.payment
     * 
     * @param payment the value for tbl_order_main.payment
     * @mbggenerated
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.create_time
     * 
     * @return the value of tbl_order_main.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.create_time
     * 
     * @param createTime the value for tbl_order_main.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.reserve_time
     * 
     * @return the value of tbl_order_main.reserve_time
     * @mbggenerated
     */
    public Date getReserveTime() {
        return reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.reserve_time
     * 
     * @param reserveTime the value for tbl_order_main.reserve_time
     * @mbggenerated
     */
    public void setReserveTime(Date reserveTime) {
        this.reserveTime = reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.total_giving_scores
     * 
     * @return the value of tbl_order_main.total_giving_scores
     * @mbggenerated
     */
    public Integer getTotalGivingScores() {
        return totalGivingScores;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.total_giving_scores
     * 
     * @param totalGivingScores the value for tbl_order_main.total_giving_scores
     * @mbggenerated
     */
    public void setTotalGivingScores(Integer totalGivingScores) {
        this.totalGivingScores = totalGivingScores;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.promotional_programs
     * 
     * @return the value of tbl_order_main.promotional_programs
     * @mbggenerated
     */
    public String getPromotionalPrograms() {
        return promotionalPrograms;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.promotional_programs
     * 
     * @param promotionalPrograms the value for tbl_order_main.promotional_programs
     * @mbggenerated
     */
    public void setPromotionalPrograms(String promotionalPrograms) {
        this.promotionalPrograms = promotionalPrograms == null ? null : promotionalPrograms.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.total_preferential_amount
     * 
     * @return the value of tbl_order_main.total_preferential_amount
     * @mbggenerated
     */
    public Double getTotalPreferentialAmount() {
        return totalPreferentialAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.total_preferential_amount
     * 
     * @param totalPreferentialAmount the value for tbl_order_main.total_preferential_amount
     * @mbggenerated
     */
    public void setTotalPreferentialAmount(Double totalPreferentialAmount) {
        this.totalPreferentialAmount = totalPreferentialAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.order_message
     * 
     * @return the value of tbl_order_main.order_message
     * @mbggenerated
     */
    public String getOrderMessage() {
        return orderMessage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.order_message
     * 
     * @param orderMessage the value for tbl_order_main.order_message
     * @mbggenerated
     */
    public void setOrderMessage(String orderMessage) {
        this.orderMessage = orderMessage == null ? null : orderMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.del_flag
     * 
     * @return the value of tbl_order_main.del_flag
     * @mbggenerated
     */
    public Short getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.del_flag
     * 
     * @param delFlag the value for tbl_order_main.del_flag
     * @mbggenerated
     */
    public void setDelFlag(Short delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.split_flag
     * 
     * @return the value of tbl_order_main.split_flag
     * @mbggenerated
     */
    public Short getSplitFlag() {
        return splitFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.split_flag
     * 
     * @param splitFlag the value for tbl_order_main.split_flag
     * @mbggenerated
     */
    public void setSplitFlag(Short splitFlag) {
        this.splitFlag = splitFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.order_flag
     * 
     * @return the value of tbl_order_main.order_flag
     * @mbggenerated
     */
    public Integer getOrderFlag() {
        return orderFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.order_flag
     * 
     * @param orderFlag the value for tbl_order_main.order_flag
     * @mbggenerated
     */
    public void setOrderFlag(Integer orderFlag) {
        this.orderFlag = orderFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.union_type
     * 
     * @return the value of tbl_order_main.union_type
     * @mbggenerated
     */
    public Integer getUnionType() {
        return unionType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.union_type
     * 
     * @param unionType the value for tbl_order_main.union_type
     * @mbggenerated
     */
    public void setUnionType(Integer unionType) {
        this.unionType = unionType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.lock_user
     * 
     * @return the value of tbl_order_main.lock_user
     * @mbggenerated
     */
    public String getLockUser() {
        return lockUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.lock_user
     * 
     * @param lockUser the value for tbl_order_main.lock_user
     * @mbggenerated
     */
    public void setLockUser(String lockUser) {
        this.lockUser = lockUser == null ? null : lockUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.pay_status
     * 
     * @return the value of tbl_order_main.pay_status
     * @mbggenerated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.pay_status
     * 
     * @param payStatus the value for tbl_order_main.pay_status
     * @mbggenerated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.buy_id
     * 
     * @return the value of tbl_order_main.buy_id
     * @mbggenerated
     */
    public String getBuyId() {
        return buyId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.buy_id
     * 
     * @param buyId the value for tbl_order_main.buy_id
     * @mbggenerated
     */
    public void setBuyId(String buyId) {
        this.buyId = buyId == null ? null : buyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.coupons_no
     * 
     * @return the value of tbl_order_main.coupons_no
     * @mbggenerated
     */
    public String getCouponsNo() {
        return couponsNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.coupons_no
     * 
     * @param couponsNo the value for tbl_order_main.coupons_no
     * @mbggenerated
     */
    public void setCouponsNo(String couponsNo) {
        this.couponsNo = couponsNo == null ? null : couponsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.consignee_id
     * 
     * @return the value of tbl_order_main.consignee_id
     * @mbggenerated
     */
    public String getConsigneeId() {
        return consigneeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.consignee_id
     * 
     * @param consigneeId the value for tbl_order_main.consignee_id
     * @mbggenerated
     */
    public void setConsigneeId(String consigneeId) {
        this.consigneeId = consigneeId == null ? null : consigneeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.online_pay_amount
     * 
     * @return the value of tbl_order_main.online_pay_amount
     * @mbggenerated
     */
    public Double getOnlinePayAmount() {
        return onlinePayAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.online_pay_amount
     * 
     * @param onlinePayAmount the value for tbl_order_main.online_pay_amount
     * @mbggenerated
     */
    public void setOnlinePayAmount(Double onlinePayAmount) {
        this.onlinePayAmount = onlinePayAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.client_sign
     * 
     * @return the value of tbl_order_main.client_sign
     * @mbggenerated
     */
    public String getClientSign() {
        return clientSign;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.client_sign
     * 
     * @param clientSign the value for tbl_order_main.client_sign
     * @mbggenerated
     */
    public void setClientSign(String clientSign) {
        this.clientSign = clientSign == null ? null : clientSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.order_total_amt
     * 
     * @return the value of tbl_order_main.order_total_amt
     * @mbggenerated
     */
    public Double getOrderTotalAmt() {
        return orderTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.order_total_amt
     * 
     * @param orderTotalAmt the value for tbl_order_main.order_total_amt
     * @mbggenerated
     */
    public void setOrderTotalAmt(Double orderTotalAmt) {
        this.orderTotalAmt = orderTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.should_postage
     * 
     * @return the value of tbl_order_main.should_postage
     * @mbggenerated
     */
    public Double getShouldPostage() {
        return shouldPostage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.should_postage
     * 
     * @param shouldPostage the value for tbl_order_main.should_postage
     * @mbggenerated
     */
    public void setShouldPostage(Double shouldPostage) {
        this.shouldPostage = shouldPostage;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.actual_postage
     * 
     * @return the value of tbl_order_main.actual_postage
     * @mbggenerated
     */
    public Double getActualPostage() {
        return actualPostage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.actual_postage
     * 
     * @param actualPostage the value for tbl_order_main.actual_postage
     * @mbggenerated
     */
    public void setActualPostage(Double actualPostage) {
        this.actualPostage = actualPostage;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_main.is_postage_free
     * 
     * @return the value of tbl_order_main.is_postage_free
     * @mbggenerated
     */
    public Integer getIsPostageFree() {
        return isPostageFree;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_main.is_postage_free
     * 
     * @param isPostageFree the value for tbl_order_main.is_postage_free
     * @mbggenerated
     */
    public void setIsPostageFree(Integer isPostageFree) {
        this.isPostageFree = isPostageFree;
    }
}
