package com.yougou.kaidian.order.model;

import java.io.Serializable;

/**
 * @author daixiaowei
 * @date 2012-03-07 10:53:36
 */
public class OrderBuyInfo implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.id
     * 
     * @mbggenerated
     */
    private String  id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.real_name
     * 
     * @mbggenerated
     */
    private String  realName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.member_name
     * 
     * @mbggenerated
     */
    private String  memberName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.constact_phone
     * 
     * @mbggenerated
     */
    private String  constactPhone;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.email
     * 
     * @mbggenerated
     */
    private String  email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.area
     * 
     * @mbggenerated
     */
    private String  area;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.zip_code
     * 
     * @mbggenerated
     */
    private String  zipCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.buy_address
     * 
     * @mbggenerated
     */
    private String  buyAddress;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.province
     * 
     * @mbggenerated
     */
    private String  province;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.city
     * 
     * @mbggenerated
     */
    private String  city;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.del_flag
     * 
     * @mbggenerated
     */
    private Short   delFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.split_flag
     * 
     * @mbggenerated
     */
    private Short   splitFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.buy_no
     * 
     * @mbggenerated
     */
    private String  buyNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.order_main_no
     * 
     * @mbggenerated
     */
    private String  orderMainNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.loginaccount_id
     * 
     * @mbggenerated
     */
    private String  loginaccountId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_buy_info.attention
     * 
     * @mbggenerated
     */
    private Integer attention;

    /**
     * 客户类型 0.新顾客  1.老顾客
     */
    private Integer customerType;
    
    /**
     * 会员类型  保存下单时会员类型
     */
    private String  memberShip;
    
    public Integer getCustomerType() {
		return customerType;
	}

	public void setCustomerType(Integer customerType) {
		this.customerType = customerType;
	}

	public String getMemberShip() {
		return memberShip;
	}

	public void setMemberShip(String memberShip) {
		this.memberShip = memberShip;
	}

	/**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.id
     * 
     * @return the value of tbl_order_buy_info.id
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.id
     * 
     * @param id the value for tbl_order_buy_info.id
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.real_name
     * 
     * @return the value of tbl_order_buy_info.real_name
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.real_name
     * 
     * @param realName the value for tbl_order_buy_info.real_name
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.member_name
     * 
     * @return the value of tbl_order_buy_info.member_name
     * @mbggenerated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.member_name
     * 
     * @param memberName the value for tbl_order_buy_info.member_name
     * @mbggenerated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.constact_phone
     * 
     * @return the value of tbl_order_buy_info.constact_phone
     * @mbggenerated
     */
    public String getConstactPhone() {
        return constactPhone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.constact_phone
     * 
     * @param constactPhone the value for tbl_order_buy_info.constact_phone
     * @mbggenerated
     */
    public void setConstactPhone(String constactPhone) {
        this.constactPhone = constactPhone == null ? null : constactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.email
     * 
     * @return the value of tbl_order_buy_info.email
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.email
     * 
     * @param email the value for tbl_order_buy_info.email
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.area
     * 
     * @return the value of tbl_order_buy_info.area
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.area
     * 
     * @param area the value for tbl_order_buy_info.area
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.zip_code
     * 
     * @return the value of tbl_order_buy_info.zip_code
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.zip_code
     * 
     * @param zipCode the value for tbl_order_buy_info.zip_code
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.buy_address
     * 
     * @return the value of tbl_order_buy_info.buy_address
     * @mbggenerated
     */
    public String getBuyAddress() {
        return buyAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.buy_address
     * 
     * @param buyAddress the value for tbl_order_buy_info.buy_address
     * @mbggenerated
     */
    public void setBuyAddress(String buyAddress) {
        this.buyAddress = buyAddress == null ? null : buyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.province
     * 
     * @return the value of tbl_order_buy_info.province
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.province
     * 
     * @param province the value for tbl_order_buy_info.province
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.city
     * 
     * @return the value of tbl_order_buy_info.city
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.city
     * 
     * @param city the value for tbl_order_buy_info.city
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.del_flag
     * 
     * @return the value of tbl_order_buy_info.del_flag
     * @mbggenerated
     */
    public Short getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.del_flag
     * 
     * @param delFlag the value for tbl_order_buy_info.del_flag
     * @mbggenerated
     */
    public void setDelFlag(Short delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.split_flag
     * 
     * @return the value of tbl_order_buy_info.split_flag
     * @mbggenerated
     */
    public Short getSplitFlag() {
        return splitFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.split_flag
     * 
     * @param splitFlag the value for tbl_order_buy_info.split_flag
     * @mbggenerated
     */
    public void setSplitFlag(Short splitFlag) {
        this.splitFlag = splitFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.buy_no
     * 
     * @return the value of tbl_order_buy_info.buy_no
     * @mbggenerated
     */
    public String getBuyNo() {
        return buyNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.buy_no
     * 
     * @param buyNo the value for tbl_order_buy_info.buy_no
     * @mbggenerated
     */
    public void setBuyNo(String buyNo) {
        this.buyNo = buyNo == null ? null : buyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.order_main_no
     * 
     * @return the value of tbl_order_buy_info.order_main_no
     * @mbggenerated
     */
    public String getOrderMainNo() {
        return orderMainNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.order_main_no
     * 
     * @param orderMainNo the value for tbl_order_buy_info.order_main_no
     * @mbggenerated
     */
    public void setOrderMainNo(String orderMainNo) {
        this.orderMainNo = orderMainNo == null ? null : orderMainNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.loginaccount_id
     * 
     * @return the value of tbl_order_buy_info.loginaccount_id
     * @mbggenerated
     */
    public String getLoginaccountId() {
        return loginaccountId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.loginaccount_id
     * 
     * @param loginaccountId the value for tbl_order_buy_info.loginaccount_id
     * @mbggenerated
     */
    public void setLoginaccountId(String loginaccountId) {
        this.loginaccountId = loginaccountId == null ? null : loginaccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_buy_info.attention
     * 
     * @return the value of tbl_order_buy_info.attention
     * @mbggenerated
     */
    public Integer getAttention() {
        return attention;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_buy_info.attention
     * 
     * @param attention the value for tbl_order_buy_info.attention
     * @mbggenerated
     */
    public void setAttention(Integer attention) {
        this.attention = attention;
    }
}
