/******************************************************************************
 * Copyright (C) 2011 YouGou Information Technology Co.,Ltd All Rights Reserved. 本软件为优购科技开发研制。未经本公司正式书面同意，其他任何个人、团体不得使用、
 * 复制、修改或发布本软件.
 *****************************************************************************/
package com.yougou.kaidian.order.model;

import java.io.Serializable;
import java.util.Date;

/**
 * @author daixiaowei
 * @date 2012-03-07 10:53:36
 */
public class OrderSub implements Serializable {

	/**
     * 
     */
	private static final long serialVersionUID = 1L;

	private String id;

	/**
	 * 父订单
	 * 
	 * @mbggenerated
	 */
	private String orderMainId;

	/**
	 * 购买人
	 * 
	 * @mbggenerated
	 */
	private String buyId;

	private String consigneeId;

	/**
	 * 发票ID
	 * 
	 * @mbggenerated
	 */
	private String invoiceId;

	/**
	 * 订单编号
	 * 
	 * @mbggenerated
	 */
	private String orderSubNo;

	/**
	 * 父订单编号
	 * 
	 * @mbggenerated
	 */
	private String orderMainNo;

	/**
	 * 优惠券编号
	 * 
	 * @mbggenerated
	 */
	private String couponsNo;

	/**
	 * 赠送积分
	 * 
	 * @mbggenerated
	 */
	private Integer givingScores;

	/**
	 * 总优惠金额
	 * 
	 * @mbggenerated
	 */
	private Double discountAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.active_name 活动名称
	 * 
	 * @mbggenerated
	 */
	private String activeName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.original_order_no 原订单号
	 * 
	 * @mbggenerated
	 */
	private String originalOrderNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.modity_date 修改日期
	 * 
	 * @mbggenerated
	 */
	private Date modityDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.create_time 创建日期
	 * 
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.order_timestamp 时间撮
	 * 
	 * @mbggenerated
	 */
	private Long orderTimestamp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.total_price 商品总金额 (减了优惠金额，没有加运费
	 * 保持与购物车一至)
	 * 
	 * @mbggenerated
	 */
	private Double totalPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.pay_status 支付状态
	 * 
	 * @mbggenerated
	 */
	private Integer payStatus = 7;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.delivery_status 配送状态
	 * 
	 * @mbggenerated
	 */
	private Integer deliveryStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.base_status 基本状态
	 * 
	 * @mbggenerated
	 */
	private Integer baseStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.lock_user 锁定用户
	 * 
	 * @mbggenerated
	 */
	private String lockUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.is_bill 是否开发票
	 * 
	 * @mbggenerated
	 */
	private Integer isBill = 1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.is_exception 是否是异常订单
	 * 
	 * @mbggenerated
	 */
	private Integer isException = 0;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.refund_amount 可退款金额
	 * 
	 * @mbggenerated
	 */
	private Double refundAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.warehouse_code 仓库编号
	 * 
	 * @mbggenerated
	 */
	private String warehouseCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.product_total_price 商品总价格 没有减优惠金额
	 * 
	 * @mbggenerated
	 */
	private Double productTotalPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.product_total_quantity 商品总数
	 * 
	 * @mbggenerated
	 */
	private Integer productTotalQuantity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.product_weight 商品重量
	 * 
	 * @mbggenerated
	 */
	private Double productWeight;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.product_weight_unit 商品重量单位
	 * 
	 * @mbggenerated
	 */
	private Integer productWeightUnit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.del_flag 删除标志
	 * 
	 * @mbggenerated
	 */
	private Short delFlag = 1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.split_flag 拆分标志
	 * 
	 * @mbggenerated
	 */
	private Short splitFlag = 1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.payment 支付方式
	 * 
	 * @mbggenerated
	 */
	private String payment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.return_goods_status 退货状态
	 * 
	 * @mbggenerated
	 */
	private Integer returnGoodsStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.apportion_status apportion_status
	 * 标识未付款提醒邮件或短信是否发送 1， 是 null， 否
	 * 
	 * @mbggenerated
	 */
	private Integer apportionStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.order_flag
	 * 
	 * @mbggenerated
	 */
	private Integer orderFlag = 1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.union_trace_code 联盟商跟踪标识，判断是否是联盟商 add
	 * 20110530_1501 by duansiyuan
	 * 
	 * @mbggenerated
	 */
	private String unionTraceCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.suspend_type
	 * 
	 * @mbggenerated
	 */
	private Integer suspendType = 0;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.message
	 * 
	 * @mbggenerated
	 */
	private String message;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.pay_total_price 换货订单支付总金额 add xu.nh by
	 * 20110607_1055 用于换货 换货计算公式：订单支付总金额 = 换货订单总金额 - 原订单支付总金额 - 质检损害金额
	 * 
	 * @mbggenerated
	 */
	private Double payTotalPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.is_derived 加盟平台 判断订单是否导出 lizhun
	 * 20110608
	 * 
	 * @mbggenerated
	 */
	private Integer isDerived;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.warehouse_delivery_status 加盟平台
	 * 标识地区仓库配送状态 lizhun 02110608
	 * 
	 * @mbggenerated
	 */
	private Integer warehouseDeliveryStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.send_or_pay_timestamp 订单发货更新时间戳
	 * 
	 * @mbggenerated
	 */
	private Long sendOrPayTimestamp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.express_order_id 快递单号
	 * 
	 * @mbggenerated
	 */
	private String expressOrderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.logistics_name 快递公司
	 * 
	 * @mbggenerated
	 */
	private String logisticsName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.order_pay_total_amont
	 * 
	 * @mbggenerated
	 */
	private Double orderPayTotalAmont;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.logistics_code 快递公司编号
	 * 
	 * @mbggenerated
	 */
	private String logisticsCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.product_send_quantity
	 * 
	 * @mbggenerated
	 */
	private Integer productSendQuantity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.off_pay_timestamp 订单线下支付时间戳
	 * 
	 * @mbggenerated
	 */
	private Long offPayTimestamp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.online_pay_amount 在线支付 已支付金额
	 * 
	 * @mbggenerated
	 */
	private Double onlinePayAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.online_payment 在线支付方式
	 * 
	 * @mbggenerated
	 */
	private String onlinePayment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.active_pref_amount
	 * 
	 * @mbggenerated
	 */
	private Double activePrefAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.member_pref_amount
	 * 
	 * @mbggenerated
	 */
	private Double memberPrefAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.coupon_pref_amount
	 * 
	 * @mbggenerated
	 */
	private Double couponPrefAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.is_sync
	 * 
	 * @mbggenerated
	 */

	private Double couponPrefAmount5;
	private Short isSync = 0;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.temp_sale_amount
	 * 
	 * @mbggenerated
	 */
	private Double tempSaleAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.client_ip
	 * 
	 * @mbggenerated
	 */
	private String clientIp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.out_order_id
	 * 
	 * @mbggenerated
	 */
	private String outOrderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.out_shop_name
	 * 
	 * @mbggenerated
	 */
	private String outShopName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.client_sign
	 * 
	 * @mbggenerated
	 */
	private String clientSign;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.cod
	 * 
	 * @mbggenerated
	 */
	private String cod;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.order_sync_time
	 * 
	 * @mbggenerated
	 */
	private Date orderSyncTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.online_pay_time
	 * 
	 * @mbggenerated
	 */
	private Date onlinePayTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.verify_user 审核人
	 * 
	 * @mbggenerated
	 */
	private String verifyUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.verify_time
	 * 
	 * @mbggenerated
	 */
	private Date verifyTime;

	private String orderSourceNo;
	private String orderSourceName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.should_postage
	 * 
	 * @mbggenerated
	 */
	private Double shouldPostage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.actual_postage
	 * 
	 * @mbggenerated
	 */
	private Double actualPostage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.payment_pref_amount
	 * 
	 * @mbggenerated
	 */
	private Double paymentPrefAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tbl_order_sub.is_postage_free
	 * 
	 * @mbggenerated
	 */
	private Integer isPostageFree;

	/**
	 * 下单立减优惠金额
	 */
	private Double buyReductionPrefAmount;

	/** 发货时间 */
	private Date shipTime;

	public Date getShipTime() {
		return shipTime;
	}

	public void setShipTime(Date shipTime) {
		this.shipTime = shipTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.id
	 * 
	 * @return the value of tbl_order_sub.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.id
	 * 
	 * @param id
	 *            the value for tbl_order_sub.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.order_main_id
	 * 
	 * @return the value of tbl_order_sub.order_main_id
	 * @mbggenerated
	 */
	public String getOrderMainId() {
		return orderMainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.order_main_id
	 * 
	 * @param orderMainId
	 *            the value for tbl_order_sub.order_main_id
	 * @mbggenerated
	 */
	public void setOrderMainId(String orderMainId) {
		this.orderMainId = orderMainId == null ? null : orderMainId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.buy_id
	 * 
	 * @return the value of tbl_order_sub.buy_id
	 * @mbggenerated
	 */
	public String getBuyId() {
		return buyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.buy_id
	 * 
	 * @param buyId
	 *            the value for tbl_order_sub.buy_id
	 * @mbggenerated
	 */
	public void setBuyId(String buyId) {
		this.buyId = buyId == null ? null : buyId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.consignee_id
	 * 
	 * @return the value of tbl_order_sub.consignee_id
	 * @mbggenerated
	 */
	public String getConsigneeId() {
		return consigneeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.consignee_id
	 * 
	 * @param consigneeId
	 *            the value for tbl_order_sub.consignee_id
	 * @mbggenerated
	 */
	public void setConsigneeId(String consigneeId) {
		this.consigneeId = consigneeId == null ? null : consigneeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.invoice_id
	 * 
	 * @return the value of tbl_order_sub.invoice_id
	 * @mbggenerated
	 */
	public String getInvoiceId() {
		return invoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.invoice_id
	 * 
	 * @param invoiceId
	 *            the value for tbl_order_sub.invoice_id
	 * @mbggenerated
	 */
	public void setInvoiceId(String invoiceId) {
		this.invoiceId = invoiceId == null ? null : invoiceId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.order_sub_no
	 * 
	 * @return the value of tbl_order_sub.order_sub_no
	 * @mbggenerated
	 */
	public String getOrderSubNo() {
		return orderSubNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.order_sub_no
	 * 
	 * @param orderSubNo
	 *            the value for tbl_order_sub.order_sub_no
	 * @mbggenerated
	 */
	public void setOrderSubNo(String orderSubNo) {
		this.orderSubNo = orderSubNo == null ? null : orderSubNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.order_main_no
	 * 
	 * @return the value of tbl_order_sub.order_main_no
	 * @mbggenerated
	 */
	public String getOrderMainNo() {
		return orderMainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.order_main_no
	 * 
	 * @param orderMainNo
	 *            the value for tbl_order_sub.order_main_no
	 * @mbggenerated
	 */
	public void setOrderMainNo(String orderMainNo) {
		this.orderMainNo = orderMainNo == null ? null : orderMainNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.coupons_no
	 * 
	 * @return the value of tbl_order_sub.coupons_no
	 * @mbggenerated
	 */
	public String getCouponsNo() {
		return couponsNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.coupons_no
	 * 
	 * @param couponsNo
	 *            the value for tbl_order_sub.coupons_no
	 * @mbggenerated
	 */
	public void setCouponsNo(String couponsNo) {
		this.couponsNo = couponsNo == null ? null : couponsNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.giving_scores
	 * 
	 * @return the value of tbl_order_sub.giving_scores
	 * @mbggenerated
	 */
	public Integer getGivingScores() {
		return givingScores;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.giving_scores
	 * 
	 * @param givingScores
	 *            the value for tbl_order_sub.giving_scores
	 * @mbggenerated
	 */
	public void setGivingScores(Integer givingScores) {
		this.givingScores = givingScores;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.discount_amount
	 * 
	 * @return the value of tbl_order_sub.discount_amount
	 * @mbggenerated
	 */
	public Double getDiscountAmount() {
		return discountAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.discount_amount
	 * 
	 * @param discountAmount
	 *            the value for tbl_order_sub.discount_amount
	 * @mbggenerated
	 */
	public void setDiscountAmount(Double discountAmount) {
		this.discountAmount = discountAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.active_name
	 * 
	 * @return the value of tbl_order_sub.active_name
	 * @mbggenerated
	 */
	public String getActiveName() {
		return activeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.active_name
	 * 
	 * @param activeName
	 *            the value for tbl_order_sub.active_name
	 * @mbggenerated
	 */
	public void setActiveName(String activeName) {
		this.activeName = activeName == null ? null : activeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.original_order_no
	 * 
	 * @return the value of tbl_order_sub.original_order_no
	 * @mbggenerated
	 */
	public String getOriginalOrderNo() {
		return originalOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.original_order_no
	 * 
	 * @param originalOrderNo
	 *            the value for tbl_order_sub.original_order_no
	 * @mbggenerated
	 */
	public void setOriginalOrderNo(String originalOrderNo) {
		this.originalOrderNo = originalOrderNo == null ? null : originalOrderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.modity_date
	 * 
	 * @return the value of tbl_order_sub.modity_date
	 * @mbggenerated
	 */
	public Date getModityDate() {
		return modityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.modity_date
	 * 
	 * @param modityDate
	 *            the value for tbl_order_sub.modity_date
	 * @mbggenerated
	 */
	public void setModityDate(Date modityDate) {
		this.modityDate = modityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.create_time
	 * 
	 * @return the value of tbl_order_sub.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.create_time
	 * 
	 * @param createTime
	 *            the value for tbl_order_sub.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.order_timestamp
	 * 
	 * @return the value of tbl_order_sub.order_timestamp
	 * @mbggenerated
	 */
	public Long getOrderTimestamp() {
		return orderTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.order_timestamp
	 * 
	 * @param orderTimestamp
	 *            the value for tbl_order_sub.order_timestamp
	 * @mbggenerated
	 */
	public void setOrderTimestamp(Long orderTimestamp) {
		this.orderTimestamp = orderTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.total_price
	 * 
	 * @return the value of tbl_order_sub.total_price
	 * @mbggenerated
	 */
	public Double getTotalPrice() {
		return totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.total_price
	 * 
	 * @param totalPrice
	 *            the value for tbl_order_sub.total_price
	 * @mbggenerated
	 */
	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.pay_status
	 * 
	 * @return the value of tbl_order_sub.pay_status
	 * @mbggenerated
	 */
	public Integer getPayStatus() {
		return payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.pay_status
	 * 
	 * @param payStatus
	 *            the value for tbl_order_sub.pay_status
	 * @mbggenerated
	 */
	public void setPayStatus(Integer payStatus) {
		this.payStatus = payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.delivery_status
	 * 
	 * @return the value of tbl_order_sub.delivery_status
	 * @mbggenerated
	 */
	public Integer getDeliveryStatus() {
		return deliveryStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.delivery_status
	 * 
	 * @param deliveryStatus
	 *            the value for tbl_order_sub.delivery_status
	 * @mbggenerated
	 */
	public void setDeliveryStatus(Integer deliveryStatus) {
		this.deliveryStatus = deliveryStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.base_status
	 * 
	 * @return the value of tbl_order_sub.base_status
	 * @mbggenerated
	 */
	public Integer getBaseStatus() {
		return baseStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.base_status
	 * 
	 * @param baseStatus
	 *            the value for tbl_order_sub.base_status
	 * @mbggenerated
	 */
	public void setBaseStatus(Integer baseStatus) {
		this.baseStatus = baseStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.lock_user
	 * 
	 * @return the value of tbl_order_sub.lock_user
	 * @mbggenerated
	 */
	public String getLockUser() {
		return lockUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.lock_user
	 * 
	 * @param lockUser
	 *            the value for tbl_order_sub.lock_user
	 * @mbggenerated
	 */
	public void setLockUser(String lockUser) {
		this.lockUser = lockUser == null ? null : lockUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.is_bill
	 * 
	 * @return the value of tbl_order_sub.is_bill
	 * @mbggenerated
	 */
	public Integer getIsBill() {
		return isBill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.is_bill
	 * 
	 * @param isBill
	 *            the value for tbl_order_sub.is_bill
	 * @mbggenerated
	 */
	public void setIsBill(Integer isBill) {
		this.isBill = isBill;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.is_exception
	 * 
	 * @return the value of tbl_order_sub.is_exception
	 * @mbggenerated
	 */
	public Integer getIsException() {
		return isException;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.is_exception
	 * 
	 * @param isException
	 *            the value for tbl_order_sub.is_exception
	 * @mbggenerated
	 */
	public void setIsException(Integer isException) {
		this.isException = isException;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.refund_amount
	 * 
	 * @return the value of tbl_order_sub.refund_amount
	 * @mbggenerated
	 */
	public Double getRefundAmount() {
		return refundAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.refund_amount
	 * 
	 * @param refundAmount
	 *            the value for tbl_order_sub.refund_amount
	 * @mbggenerated
	 */
	public void setRefundAmount(Double refundAmount) {
		this.refundAmount = refundAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.warehouse_code
	 * 
	 * @return the value of tbl_order_sub.warehouse_code
	 * @mbggenerated
	 */
	public String getWarehouseCode() {
		return warehouseCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.warehouse_code
	 * 
	 * @param warehouseCode
	 *            the value for tbl_order_sub.warehouse_code
	 * @mbggenerated
	 */
	public void setWarehouseCode(String warehouseCode) {
		this.warehouseCode = warehouseCode == null ? null : warehouseCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.product_total_price
	 * 
	 * @return the value of tbl_order_sub.product_total_price
	 * @mbggenerated
	 */
	public Double getProductTotalPrice() {
		return productTotalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.product_total_price
	 * 
	 * @param productTotalPrice
	 *            the value for tbl_order_sub.product_total_price
	 * @mbggenerated
	 */
	public void setProductTotalPrice(Double productTotalPrice) {
		this.productTotalPrice = productTotalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.product_total_quantity
	 * 
	 * @return the value of tbl_order_sub.product_total_quantity
	 * @mbggenerated
	 */
	public Integer getProductTotalQuantity() {
		return productTotalQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.product_total_quantity
	 * 
	 * @param productTotalQuantity
	 *            the value for tbl_order_sub.product_total_quantity
	 * @mbggenerated
	 */
	public void setProductTotalQuantity(Integer productTotalQuantity) {
		this.productTotalQuantity = productTotalQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.product_weight
	 * 
	 * @return the value of tbl_order_sub.product_weight
	 * @mbggenerated
	 */
	public Double getProductWeight() {
		return productWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.product_weight
	 * 
	 * @param productWeight
	 *            the value for tbl_order_sub.product_weight
	 * @mbggenerated
	 */
	public void setProductWeight(Double productWeight) {
		this.productWeight = productWeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.product_weight_unit
	 * 
	 * @return the value of tbl_order_sub.product_weight_unit
	 * @mbggenerated
	 */
	public Integer getProductWeightUnit() {
		return productWeightUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.product_weight_unit
	 * 
	 * @param productWeightUnit
	 *            the value for tbl_order_sub.product_weight_unit
	 * @mbggenerated
	 */
	public void setProductWeightUnit(Integer productWeightUnit) {
		this.productWeightUnit = productWeightUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.del_flag
	 * 
	 * @return the value of tbl_order_sub.del_flag
	 * @mbggenerated
	 */
	public Short getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.del_flag
	 * 
	 * @param delFlag
	 *            the value for tbl_order_sub.del_flag
	 * @mbggenerated
	 */
	public void setDelFlag(Short delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.split_flag
	 * 
	 * @return the value of tbl_order_sub.split_flag
	 * @mbggenerated
	 */
	public Short getSplitFlag() {
		return splitFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.split_flag
	 * 
	 * @param splitFlag
	 *            the value for tbl_order_sub.split_flag
	 * @mbggenerated
	 */
	public void setSplitFlag(Short splitFlag) {
		this.splitFlag = splitFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.payment
	 * 
	 * @return the value of tbl_order_sub.payment
	 * @mbggenerated
	 */
	public String getPayment() {
		return payment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.payment
	 * 
	 * @param payment
	 *            the value for tbl_order_sub.payment
	 * @mbggenerated
	 */
	public void setPayment(String payment) {
		this.payment = payment == null ? null : payment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.return_goods_status
	 * 
	 * @return the value of tbl_order_sub.return_goods_status
	 * @mbggenerated
	 */
	public Integer getReturnGoodsStatus() {
		return returnGoodsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.return_goods_status
	 * 
	 * @param returnGoodsStatus
	 *            the value for tbl_order_sub.return_goods_status
	 * @mbggenerated
	 */
	public void setReturnGoodsStatus(Integer returnGoodsStatus) {
		this.returnGoodsStatus = returnGoodsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.apportion_status
	 * 
	 * @return the value of tbl_order_sub.apportion_status
	 * @mbggenerated
	 */
	public Integer getApportionStatus() {
		return apportionStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.apportion_status
	 * 
	 * @param apportionStatus
	 *            the value for tbl_order_sub.apportion_status
	 * @mbggenerated
	 */
	public void setApportionStatus(Integer apportionStatus) {
		this.apportionStatus = apportionStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.order_flag
	 * 
	 * @return the value of tbl_order_sub.order_flag
	 * @mbggenerated
	 */
	public Integer getOrderFlag() {
		return orderFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.order_flag
	 * 
	 * @param orderFlag
	 *            the value for tbl_order_sub.order_flag
	 * @mbggenerated
	 */
	public void setOrderFlag(Integer orderFlag) {
		this.orderFlag = orderFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.union_trace_code
	 * 
	 * @return the value of tbl_order_sub.union_trace_code
	 * @mbggenerated
	 */
	public String getUnionTraceCode() {
		return unionTraceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.union_trace_code
	 * 
	 * @param unionTraceCode
	 *            the value for tbl_order_sub.union_trace_code
	 * @mbggenerated
	 */
	public void setUnionTraceCode(String unionTraceCode) {
		this.unionTraceCode = unionTraceCode == null ? null : unionTraceCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.suspend_type
	 * 
	 * @return the value of tbl_order_sub.suspend_type
	 * @mbggenerated
	 */
	public Integer getSuspendType() {
		return suspendType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.suspend_type
	 * 
	 * @param suspendType
	 *            the value for tbl_order_sub.suspend_type
	 * @mbggenerated
	 */
	public void setSuspendType(Integer suspendType) {
		this.suspendType = suspendType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.message
	 * 
	 * @return the value of tbl_order_sub.message
	 * @mbggenerated
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.message
	 * 
	 * @param message
	 *            the value for tbl_order_sub.message
	 * @mbggenerated
	 */
	public void setMessage(String message) {
		this.message = message == null ? null : message.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.pay_total_price
	 * 
	 * @return the value of tbl_order_sub.pay_total_price
	 * @mbggenerated
	 */
	public Double getPayTotalPrice() {
		return payTotalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.pay_total_price
	 * 
	 * @param payTotalPrice
	 *            the value for tbl_order_sub.pay_total_price
	 * @mbggenerated
	 */
	public void setPayTotalPrice(Double payTotalPrice) {
		this.payTotalPrice = payTotalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.is_derived
	 * 
	 * @return the value of tbl_order_sub.is_derived
	 * @mbggenerated
	 */
	public Integer getIsDerived() {
		return isDerived;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.is_derived
	 * 
	 * @param isDerived
	 *            the value for tbl_order_sub.is_derived
	 * @mbggenerated
	 */
	public void setIsDerived(Integer isDerived) {
		this.isDerived = isDerived;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.warehouse_delivery_status
	 * 
	 * @return the value of tbl_order_sub.warehouse_delivery_status
	 * @mbggenerated
	 */
	public Integer getWarehouseDeliveryStatus() {
		return warehouseDeliveryStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.warehouse_delivery_status
	 * 
	 * @param warehouseDeliveryStatus
	 *            the value for tbl_order_sub.warehouse_delivery_status
	 * @mbggenerated
	 */
	public void setWarehouseDeliveryStatus(Integer warehouseDeliveryStatus) {
		this.warehouseDeliveryStatus = warehouseDeliveryStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.send_or_pay_timestamp
	 * 
	 * @return the value of tbl_order_sub.send_or_pay_timestamp
	 * @mbggenerated
	 */
	public Long getSendOrPayTimestamp() {
		return sendOrPayTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.send_or_pay_timestamp
	 * 
	 * @param sendOrPayTimestamp
	 *            the value for tbl_order_sub.send_or_pay_timestamp
	 * @mbggenerated
	 */
	public void setSendOrPayTimestamp(Long sendOrPayTimestamp) {
		this.sendOrPayTimestamp = sendOrPayTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.express_order_id
	 * 
	 * @return the value of tbl_order_sub.express_order_id
	 * @mbggenerated
	 */
	public String getExpressOrderId() {
		return expressOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.express_order_id
	 * 
	 * @param expressOrderId
	 *            the value for tbl_order_sub.express_order_id
	 * @mbggenerated
	 */
	public void setExpressOrderId(String expressOrderId) {
		this.expressOrderId = expressOrderId == null ? null : expressOrderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.logistics_name
	 * 
	 * @return the value of tbl_order_sub.logistics_name
	 * @mbggenerated
	 */
	public String getLogisticsName() {
		return logisticsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.logistics_name
	 * 
	 * @param logisticsName
	 *            the value for tbl_order_sub.logistics_name
	 * @mbggenerated
	 */
	public void setLogisticsName(String logisticsName) {
		this.logisticsName = logisticsName == null ? null : logisticsName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.order_pay_total_amont
	 * 
	 * @return the value of tbl_order_sub.order_pay_total_amont
	 * @mbggenerated
	 */
	public Double getOrderPayTotalAmont() {
		return orderPayTotalAmont;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.order_pay_total_amont
	 * 
	 * @param orderPayTotalAmont
	 *            the value for tbl_order_sub.order_pay_total_amont
	 * @mbggenerated
	 */
	public void setOrderPayTotalAmont(Double orderPayTotalAmont) {
		this.orderPayTotalAmont = orderPayTotalAmont;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.logistics_code
	 * 
	 * @return the value of tbl_order_sub.logistics_code
	 * @mbggenerated
	 */
	public String getLogisticsCode() {
		return logisticsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.logistics_code
	 * 
	 * @param logisticsCode
	 *            the value for tbl_order_sub.logistics_code
	 * @mbggenerated
	 */
	public void setLogisticsCode(String logisticsCode) {
		this.logisticsCode = logisticsCode == null ? null : logisticsCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.product_send_quantity
	 * 
	 * @return the value of tbl_order_sub.product_send_quantity
	 * @mbggenerated
	 */
	public Integer getProductSendQuantity() {
		return productSendQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.product_send_quantity
	 * 
	 * @param productSendQuantity
	 *            the value for tbl_order_sub.product_send_quantity
	 * @mbggenerated
	 */
	public void setProductSendQuantity(Integer productSendQuantity) {
		this.productSendQuantity = productSendQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.off_pay_timestamp
	 * 
	 * @return the value of tbl_order_sub.off_pay_timestamp
	 * @mbggenerated
	 */
	public Long getOffPayTimestamp() {
		return offPayTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.off_pay_timestamp
	 * 
	 * @param offPayTimestamp
	 *            the value for tbl_order_sub.off_pay_timestamp
	 * @mbggenerated
	 */
	public void setOffPayTimestamp(Long offPayTimestamp) {
		this.offPayTimestamp = offPayTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.online_pay_amount
	 * 
	 * @return the value of tbl_order_sub.online_pay_amount
	 * @mbggenerated
	 */
	public Double getOnlinePayAmount() {
		return onlinePayAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.online_pay_amount
	 * 
	 * @param onlinePayAmount
	 *            the value for tbl_order_sub.online_pay_amount
	 * @mbggenerated
	 */
	public void setOnlinePayAmount(Double onlinePayAmount) {
		this.onlinePayAmount = onlinePayAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.online_payment
	 * 
	 * @return the value of tbl_order_sub.online_payment
	 * @mbggenerated
	 */
	public String getOnlinePayment() {
		return onlinePayment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.online_payment
	 * 
	 * @param onlinePayment
	 *            the value for tbl_order_sub.online_payment
	 * @mbggenerated
	 */
	public void setOnlinePayment(String onlinePayment) {
		this.onlinePayment = onlinePayment == null ? null : onlinePayment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.active_pref_amount
	 * 
	 * @return the value of tbl_order_sub.active_pref_amount
	 * @mbggenerated
	 */
	public Double getActivePrefAmount() {
		return activePrefAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.active_pref_amount
	 * 
	 * @param activePrefAmount
	 *            the value for tbl_order_sub.active_pref_amount
	 * @mbggenerated
	 */
	public void setActivePrefAmount(Double activePrefAmount) {
		this.activePrefAmount = activePrefAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.member_pref_amount
	 * 
	 * @return the value of tbl_order_sub.member_pref_amount
	 * @mbggenerated
	 */
	public Double getMemberPrefAmount() {
		return memberPrefAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.member_pref_amount
	 * 
	 * @param memberPrefAmount
	 *            the value for tbl_order_sub.member_pref_amount
	 * @mbggenerated
	 */
	public void setMemberPrefAmount(Double memberPrefAmount) {
		this.memberPrefAmount = memberPrefAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.coupon_pref_amount
	 * 
	 * @return the value of tbl_order_sub.coupon_pref_amount
	 * @mbggenerated
	 */
	public Double getCouponPrefAmount() {
		return couponPrefAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.coupon_pref_amount
	 * 
	 * @param couponPrefAmount
	 *            the value for tbl_order_sub.coupon_pref_amount
	 * @mbggenerated
	 */
	public void setCouponPrefAmount(Double couponPrefAmount) {
		this.couponPrefAmount = couponPrefAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.is_sync
	 * 
	 * @return the value of tbl_order_sub.is_sync
	 * @mbggenerated
	 */
	public Short getIsSync() {
		return isSync;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.is_sync
	 * 
	 * @param isSync
	 *            the value for tbl_order_sub.is_sync
	 * @mbggenerated
	 */
	public void setIsSync(Short isSync) {
		this.isSync = isSync;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.temp_sale_amount
	 * 
	 * @return the value of tbl_order_sub.temp_sale_amount
	 * @mbggenerated
	 */
	public Double getTempSaleAmount() {
		return tempSaleAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.temp_sale_amount
	 * 
	 * @param tempSaleAmount
	 *            the value for tbl_order_sub.temp_sale_amount
	 * @mbggenerated
	 */
	public void setTempSaleAmount(Double tempSaleAmount) {
		this.tempSaleAmount = tempSaleAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.client_ip
	 * 
	 * @return the value of tbl_order_sub.client_ip
	 * @mbggenerated
	 */
	public String getClientIp() {
		return clientIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.client_ip
	 * 
	 * @param clientIp
	 *            the value for tbl_order_sub.client_ip
	 * @mbggenerated
	 */
	public void setClientIp(String clientIp) {
		this.clientIp = clientIp == null ? null : clientIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.out_order_id
	 * 
	 * @return the value of tbl_order_sub.out_order_id
	 * @mbggenerated
	 */
	public String getOutOrderId() {
		return outOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.out_order_id
	 * 
	 * @param outOrderId
	 *            the value for tbl_order_sub.out_order_id
	 * @mbggenerated
	 */
	public void setOutOrderId(String outOrderId) {
		this.outOrderId = outOrderId == null ? null : outOrderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.out_shop_name
	 * 
	 * @return the value of tbl_order_sub.out_shop_name
	 * @mbggenerated
	 */
	public String getOutShopName() {
		return outShopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.out_shop_name
	 * 
	 * @param outShopName
	 *            the value for tbl_order_sub.out_shop_name
	 * @mbggenerated
	 */
	public void setOutShopName(String outShopName) {
		this.outShopName = outShopName == null ? null : outShopName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.client_sign
	 * 
	 * @return the value of tbl_order_sub.client_sign
	 * @mbggenerated
	 */
	public String getClientSign() {
		return clientSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.client_sign
	 * 
	 * @param clientSign
	 *            the value for tbl_order_sub.client_sign
	 * @mbggenerated
	 */
	public void setClientSign(String clientSign) {
		this.clientSign = clientSign == null ? null : clientSign.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.cod
	 * 
	 * @return the value of tbl_order_sub.cod
	 * @mbggenerated
	 */
	public String getCod() {
		return cod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.cod
	 * 
	 * @param cod
	 *            the value for tbl_order_sub.cod
	 * @mbggenerated
	 */
	public void setCod(String cod) {
		this.cod = cod == null ? null : cod.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.order_sync_time
	 * 
	 * @return the value of tbl_order_sub.order_sync_time
	 * @mbggenerated
	 */
	public Date getOrderSyncTime() {
		return orderSyncTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.order_sync_time
	 * 
	 * @param orderSyncTime
	 *            the value for tbl_order_sub.order_sync_time
	 * @mbggenerated
	 */
	public void setOrderSyncTime(Date orderSyncTime) {
		this.orderSyncTime = orderSyncTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.online_pay_time
	 * 
	 * @return the value of tbl_order_sub.online_pay_time
	 * @mbggenerated
	 */
	public Date getOnlinePayTime() {
		return onlinePayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.online_pay_time
	 * 
	 * @param onlinePayTime
	 *            the value for tbl_order_sub.online_pay_time
	 * @mbggenerated
	 */
	public void setOnlinePayTime(Date onlinePayTime) {
		this.onlinePayTime = onlinePayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.verify_user
	 * 
	 * @return the value of tbl_order_sub.verify_user
	 * @mbggenerated
	 */
	public String getVerifyUser() {
		return verifyUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.verify_user
	 * 
	 * @param verifyUser
	 *            the value for tbl_order_sub.verify_user
	 * @mbggenerated
	 */
	public void setVerifyUser(String verifyUser) {
		this.verifyUser = verifyUser == null ? null : verifyUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.verify_time
	 * 
	 * @return the value of tbl_order_sub.verify_time
	 * @mbggenerated
	 */
	public Date getVerifyTime() {
		return verifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.verify_time
	 * 
	 * @param verifyTime
	 *            the value for tbl_order_sub.verify_time
	 * @mbggenerated
	 */
	public void setVerifyTime(Date verifyTime) {
		this.verifyTime = verifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.should_postage
	 * 
	 * @return the value of tbl_order_sub.should_postage
	 * @mbggenerated
	 */
	public Double getShouldPostage() {
		return shouldPostage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.should_postage
	 * 
	 * @param shouldPostage
	 *            the value for tbl_order_sub.should_postage
	 * @mbggenerated
	 */
	public void setShouldPostage(Double shouldPostage) {
		this.shouldPostage = shouldPostage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.actual_postage
	 * 
	 * @return the value of tbl_order_sub.actual_postage
	 * @mbggenerated
	 */
	public Double getActualPostage() {
		return actualPostage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.actual_postage
	 * 
	 * @param actualPostage
	 *            the value for tbl_order_sub.actual_postage
	 * @mbggenerated
	 */
	public void setActualPostage(Double actualPostage) {
		this.actualPostage = actualPostage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.payment_pref_amount
	 * 
	 * @return the value of tbl_order_sub.payment_pref_amount
	 * @mbggenerated
	 */
	public Double getPaymentPrefAmount() {
		return paymentPrefAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.payment_pref_amount
	 * 
	 * @param paymentPrefAmount
	 *            the value for tbl_order_sub.payment_pref_amount
	 * @mbggenerated
	 */
	public void setPaymentPrefAmount(Double paymentPrefAmount) {
		this.paymentPrefAmount = paymentPrefAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tbl_order_sub.is_postage_free
	 * 
	 * @return the value of tbl_order_sub.is_postage_free
	 * @mbggenerated
	 */
	public Integer getIsPostageFree() {
		return isPostageFree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tbl_order_sub.is_postage_free
	 * 
	 * @param isPostageFree
	 *            the value for tbl_order_sub.is_postage_free
	 * @mbggenerated
	 */
	public void setIsPostageFree(Integer isPostageFree) {
		this.isPostageFree = isPostageFree;
	}

	public Double getBuyReductionPrefAmount() {
		return buyReductionPrefAmount;
	}

	public void setBuyReductionPrefAmount(Double buyReductionPrefAmount) {
		this.buyReductionPrefAmount = buyReductionPrefAmount;
	}

	public String getOrderSourceNo() {
		return orderSourceNo;
	}

	public void setOrderSourceNo(String orderSourceNo) {
		this.orderSourceNo = orderSourceNo;
	}

	public String getOrderSourceName() {
		return orderSourceName;
	}

	public void setOrderSourceName(String orderSourceName) {
		this.orderSourceName = orderSourceName;
	}

	public Double getCouponPrefAmount5() {
		return couponPrefAmount5;
	}

	public void setCouponPrefAmount5(Double couponPrefAmount5) {
		this.couponPrefAmount5 = couponPrefAmount5;
	}
}
