package com.yougou.kaidian.order.model;

import java.io.Serializable;

/**
 * @author daixiaowei
 * @date 2012-03-07 10:53:36
 */
public class OrderDetail4sub implements Serializable {

	/**
     * 
     */
    private static final long serialVersionUID = 1L;

    private String  id;

    private String  commodityId;

    private String  commodityNo;
    
    /**
     * 分类编号
     */
    private String catNo;

    private String  orderSubId;

    private String  orderMainNo;

    private String  prodNo;

    private String  prodName;

    private String  prodType;

    private String  commoditySpecificationStr;

    private Integer commodityNum;

    private Double  commodityWeight;

    private Double  prodTotalAmt;

    private String  commodityImage;

    private Short   splitFlag;

    private Short   delFlag;

    private String  subDetailNo;

    private Integer prodStatus;

    private Double  prodDiscountAmount;

    private Double  prodUnitPrice;

    private String  applyRefundNo;

    private String  levelCode;

    private Integer usableNum=-1;

    private String  giftInfo;

    private String  activeName;
    private Integer discountNumber;

    private String  discountNo;

    private Integer givingScores;

    private String  activeId;

    private Short   activeType;
    //货品类型:0.普通商品  1.赠品  2.换购
    private Integer commodityType;
    private String commodityTypeName;
    
	private Double  activePrefAmount;

    private Double  memberPrefAmount;

    private Double  couponPrefAmount;

    private Double  tempSaleAmount;

    private Double  salePrice;

    private Double  activePrice;

    private Double  paymentPrefAmount;
    
    /**
     * 下单立减优惠金额
     */
    private Double buyReductionPrefAmount;

    /**
     * 商品品牌
     */
    private String brandName;
    
	 /**
	  *  第三方条码(xls)(供应商货品条码)
	  */
	private String thirdPartyCode;
	
	/**
	 * 单品页Url
	 */
	private String prodUrl;
	
    //商品款号
	private String styleNo;
	
	//商品颜色
	private String specName;
	
	//尺码名称
	private String sizeName;
	
	public String getStyleNo() {
		return styleNo;
	}

	public void setStyleNo(String styleNo) {
		this.styleNo = styleNo;
	}

	public String getSpecName() {
		return specName;
	}

	public void setSpecName(String specName) {
		this.specName = specName;
	}

	public String getSizeName() {
		return sizeName;
	}

	public void setSizeName(String sizeName) {
		this.sizeName = sizeName;
	}

	public String getProdUrl() {
		return prodUrl;
	}

	public void setProdUrl(String prodUrl) {
		this.prodUrl = prodUrl;
	}

	public String getThirdPartyCode() {
		return thirdPartyCode;
	}

	public void setThirdPartyCode(String thirdPartyCode) {
		this.thirdPartyCode = thirdPartyCode;
	}

	public String getBrandName() {
		return brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	/**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.id
     * 
     * @return the value of tbl_order_detail4sub.id
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.id
     * 
     * @param id the value for tbl_order_detail4sub.id
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.commodity_id
     * 
     * @return the value of tbl_order_detail4sub.commodity_id
     * @mbggenerated
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.commodity_id
     * 
     * @param commodityId the value for tbl_order_detail4sub.commodity_id
     * @mbggenerated
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.commodity_no
     * 
     * @return the value of tbl_order_detail4sub.commodity_no
     * @mbggenerated
     */
    public String getCommodityNo() {
        return commodityNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.commodity_no
     * 
     * @param commodityNo the value for tbl_order_detail4sub.commodity_no
     * @mbggenerated
     */
    public void setCommodityNo(String commodityNo) {
        this.commodityNo = commodityNo == null ? null : commodityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.order_sub_id
     * 
     * @return the value of tbl_order_detail4sub.order_sub_id
     * @mbggenerated
     */
    public String getOrderSubId() {
        return orderSubId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.order_sub_id
     * 
     * @param orderSubId the value for tbl_order_detail4sub.order_sub_id
     * @mbggenerated
     */
    public void setOrderSubId(String orderSubId) {
        this.orderSubId = orderSubId == null ? null : orderSubId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.order_main_no
     * 
     * @return the value of tbl_order_detail4sub.order_main_no
     * @mbggenerated
     */
    public String getOrderMainNo() {
        return orderMainNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.order_main_no
     * 
     * @param orderMainNo the value for tbl_order_detail4sub.order_main_no
     * @mbggenerated
     */
    public void setOrderMainNo(String orderMainNo) {
        this.orderMainNo = orderMainNo == null ? null : orderMainNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.prod_no
     * 
     * @return the value of tbl_order_detail4sub.prod_no
     * @mbggenerated
     */
    public String getProdNo() {
        return prodNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.prod_no
     * 
     * @param prodNo the value for tbl_order_detail4sub.prod_no
     * @mbggenerated
     */
    public void setProdNo(String prodNo) {
        this.prodNo = prodNo == null ? null : prodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.prod_name
     * 
     * @return the value of tbl_order_detail4sub.prod_name
     * @mbggenerated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.prod_name
     * 
     * @param prodName the value for tbl_order_detail4sub.prod_name
     * @mbggenerated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.prod_type
     * 
     * @return the value of tbl_order_detail4sub.prod_type
     * @mbggenerated
     */
    public String getProdType() {
        return prodType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.prod_type
     * 
     * @param prodType the value for tbl_order_detail4sub.prod_type
     * @mbggenerated
     */
    public void setProdType(String prodType) {
        this.prodType = prodType == null ? null : prodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.commodity_specification_str
     * 
     * @return the value of tbl_order_detail4sub.commodity_specification_str
     * @mbggenerated
     */
    public String getCommoditySpecificationStr() {
        return commoditySpecificationStr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.commodity_specification_str
     * 
     * @param commoditySpecificationStr the value for tbl_order_detail4sub.commodity_specification_str
     * @mbggenerated
     */
    public void setCommoditySpecificationStr(String commoditySpecificationStr) {
        this.commoditySpecificationStr = commoditySpecificationStr == null ? null : commoditySpecificationStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.commodity_num
     * 
     * @return the value of tbl_order_detail4sub.commodity_num
     * @mbggenerated
     */
    public Integer getCommodityNum() {
        return commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.commodity_num
     * 
     * @param commodityNum the value for tbl_order_detail4sub.commodity_num
     * @mbggenerated
     */
    public void setCommodityNum(Integer commodityNum) {
        this.commodityNum = commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.commodity_weight
     * 
     * @return the value of tbl_order_detail4sub.commodity_weight
     * @mbggenerated
     */
    public Double getCommodityWeight() {
        return commodityWeight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.commodity_weight
     * 
     * @param commodityWeight the value for tbl_order_detail4sub.commodity_weight
     * @mbggenerated
     */
    public void setCommodityWeight(Double commodityWeight) {
        this.commodityWeight = commodityWeight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.prod_total_amt
     * 
     * @return the value of tbl_order_detail4sub.prod_total_amt
     * @mbggenerated
     */
    public Double getProdTotalAmt() {
        return prodTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.prod_total_amt
     * 
     * @param prodTotalAmt the value for tbl_order_detail4sub.prod_total_amt
     * @mbggenerated
     */
    public void setProdTotalAmt(Double prodTotalAmt) {
        this.prodTotalAmt = prodTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.commodity_image
     * 
     * @return the value of tbl_order_detail4sub.commodity_image
     * @mbggenerated
     */
    public String getCommodityImage() {
        return commodityImage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.commodity_image
     * 
     * @param commodityImage the value for tbl_order_detail4sub.commodity_image
     * @mbggenerated
     */
    public void setCommodityImage(String commodityImage) {
        this.commodityImage = commodityImage == null ? null : commodityImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.split_flag
     * 
     * @return the value of tbl_order_detail4sub.split_flag
     * @mbggenerated
     */
    public Short getSplitFlag() {
        return splitFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.split_flag
     * 
     * @param splitFlag the value for tbl_order_detail4sub.split_flag
     * @mbggenerated
     */
    public void setSplitFlag(Short splitFlag) {
        this.splitFlag = splitFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.del_flag
     * 
     * @return the value of tbl_order_detail4sub.del_flag
     * @mbggenerated
     */
    public Short getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.del_flag
     * 
     * @param delFlag the value for tbl_order_detail4sub.del_flag
     * @mbggenerated
     */
    public void setDelFlag(Short delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.sub_detail_no
     * 
     * @return the value of tbl_order_detail4sub.sub_detail_no
     * @mbggenerated
     */
    public String getSubDetailNo() {
        return subDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.sub_detail_no
     * 
     * @param subDetailNo the value for tbl_order_detail4sub.sub_detail_no
     * @mbggenerated
     */
    public void setSubDetailNo(String subDetailNo) {
        this.subDetailNo = subDetailNo == null ? null : subDetailNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.prod_status
     * 
     * @return the value of tbl_order_detail4sub.prod_status
     * @mbggenerated
     */
    public Integer getProdStatus() {
        return prodStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.prod_status
     * 
     * @param prodStatus the value for tbl_order_detail4sub.prod_status
     * @mbggenerated
     */
    public void setProdStatus(Integer prodStatus) {
        this.prodStatus = prodStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.prod_discount_amount
     * 
     * @return the value of tbl_order_detail4sub.prod_discount_amount
     * @mbggenerated
     */
    public Double getProdDiscountAmount() {
        return prodDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.prod_discount_amount
     * 
     * @param prodDiscountAmount the value for tbl_order_detail4sub.prod_discount_amount
     * @mbggenerated
     */
    public void setProdDiscountAmount(Double prodDiscountAmount) {
        this.prodDiscountAmount = prodDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.prod_unit_price
     * 
     * @return the value of tbl_order_detail4sub.prod_unit_price
     * @mbggenerated
     */
    public Double getProdUnitPrice() {
        return prodUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.prod_unit_price
     * 
     * @param prodUnitPrice the value for tbl_order_detail4sub.prod_unit_price
     * @mbggenerated
     */
    public void setProdUnitPrice(Double prodUnitPrice) {
        this.prodUnitPrice = prodUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.apply_refund_no
     * 
     * @return the value of tbl_order_detail4sub.apply_refund_no
     * @mbggenerated
     */
    public String getApplyRefundNo() {
        return applyRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.apply_refund_no
     * 
     * @param applyRefundNo the value for tbl_order_detail4sub.apply_refund_no
     * @mbggenerated
     */
    public void setApplyRefundNo(String applyRefundNo) {
        this.applyRefundNo = applyRefundNo == null ? null : applyRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.level_code
     * 
     * @return the value of tbl_order_detail4sub.level_code
     * @mbggenerated
     */
    public String getLevelCode() {
        return levelCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.level_code
     * 
     * @param levelCode the value for tbl_order_detail4sub.level_code
     * @mbggenerated
     */
    public void setLevelCode(String levelCode) {
        this.levelCode = levelCode == null ? null : levelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.usable_num
     * 
     * @return the value of tbl_order_detail4sub.usable_num
     * @mbggenerated
     */
    public Integer getUsableNum() {
        return usableNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.usable_num
     * 
     * @param usableNum the value for tbl_order_detail4sub.usable_num
     * @mbggenerated
     */
    public void setUsableNum(Integer usableNum) {
        this.usableNum = usableNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.gift_info
     * 
     * @return the value of tbl_order_detail4sub.gift_info
     * @mbggenerated
     */
    public String getGiftInfo() {
        return giftInfo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.gift_info
     * 
     * @param giftInfo the value for tbl_order_detail4sub.gift_info
     * @mbggenerated
     */
    public void setGiftInfo(String giftInfo) {
        this.giftInfo = giftInfo == null ? null : giftInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.active_name
     * 
     * @return the value of tbl_order_detail4sub.active_name
     * @mbggenerated
     */
    public String getActiveName() {
        return activeName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.active_name
     * 
     * @param activeName the value for tbl_order_detail4sub.active_name
     * @mbggenerated
     */
    public void setActiveName(String activeName) {
        this.activeName = activeName == null ? null : activeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.discount_number
     * 
     * @return the value of tbl_order_detail4sub.discount_number
     * @mbggenerated
     */
    public Integer getDiscountNumber() {
        return discountNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.discount_number
     * 
     * @param discountNumber the value for tbl_order_detail4sub.discount_number
     * @mbggenerated
     */
    public void setDiscountNumber(Integer discountNumber) {
        this.discountNumber = discountNumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.discount_no
     * 
     * @return the value of tbl_order_detail4sub.discount_no
     * @mbggenerated
     */
    public String getDiscountNo() {
        return discountNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.discount_no
     * 
     * @param discountNo the value for tbl_order_detail4sub.discount_no
     * @mbggenerated
     */
    public void setDiscountNo(String discountNo) {
        this.discountNo = discountNo == null ? null : discountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.giving_scores
     * 
     * @return the value of tbl_order_detail4sub.giving_scores
     * @mbggenerated
     */
    public Integer getGivingScores() {
        return givingScores;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.giving_scores
     * 
     * @param givingScores the value for tbl_order_detail4sub.giving_scores
     * @mbggenerated
     */
    public void setGivingScores(Integer givingScores) {
        this.givingScores = givingScores;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.active_id
     * 
     * @return the value of tbl_order_detail4sub.active_id
     * @mbggenerated
     */
    public String getActiveId() {
        return activeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.active_id
     * 
     * @param activeId the value for tbl_order_detail4sub.active_id
     * @mbggenerated
     */
    public void setActiveId(String activeId) {
        this.activeId = activeId == null ? null : activeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.active_type
     * 
     * @return the value of tbl_order_detail4sub.active_type
     * @mbggenerated
     */
    public Short getActiveType() {
        return activeType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.active_type
     * 
     * @param activeType the value for tbl_order_detail4sub.active_type
     * @mbggenerated
     */
    public void setActiveType(Short activeType) {
        this.activeType = activeType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.commodity_type
     * 
     * @return the value of tbl_order_detail4sub.commodity_type
     * @mbggenerated
     */
    public Integer getCommodityType() {
        return commodityType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.commodity_type
     * 
     * @param commodityType the value for tbl_order_detail4sub.commodity_type
     * @mbggenerated
     */
    public void setCommodityType(Integer commodityType) {
        this.commodityType = commodityType;
    }
    public String getCommodityTypeName() {
    	if(commodityType!=null){
    		if(commodityType==0){
    			return "普通商品";
    		}else if(commodityType==1){
    			return "赠品";
    		}else if(commodityType==2){
    			return "换购";
    		}
    	}
		return commodityTypeName;
	}

	public void setCommodityTypeName(String commodityTypeName) {
		this.commodityTypeName = commodityTypeName;
	}
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.active_pref_amount
     * 
     * @return the value of tbl_order_detail4sub.active_pref_amount
     * @mbggenerated
     */
    public Double getActivePrefAmount() {
        return activePrefAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.active_pref_amount
     * 
     * @param activePrefAmount the value for tbl_order_detail4sub.active_pref_amount
     * @mbggenerated
     */
    public void setActivePrefAmount(Double activePrefAmount) {
        this.activePrefAmount = activePrefAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.member_pref_amount
     * 
     * @return the value of tbl_order_detail4sub.member_pref_amount
     * @mbggenerated
     */
    public Double getMemberPrefAmount() {
        return memberPrefAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.member_pref_amount
     * 
     * @param memberPrefAmount the value for tbl_order_detail4sub.member_pref_amount
     * @mbggenerated
     */
    public void setMemberPrefAmount(Double memberPrefAmount) {
        this.memberPrefAmount = memberPrefAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.coupon_pref_amount
     * 
     * @return the value of tbl_order_detail4sub.coupon_pref_amount
     * @mbggenerated
     */
    public Double getCouponPrefAmount() {
        return couponPrefAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.coupon_pref_amount
     * 
     * @param couponPrefAmount the value for tbl_order_detail4sub.coupon_pref_amount
     * @mbggenerated
     */
    public void setCouponPrefAmount(Double couponPrefAmount) {
        this.couponPrefAmount = couponPrefAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.temp_sale_amount
     * 
     * @return the value of tbl_order_detail4sub.temp_sale_amount
     * @mbggenerated
     */
    public Double getTempSaleAmount() {
        return tempSaleAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4sub.temp_sale_amount
     * 
     * @param tempSaleAmount the value for tbl_order_detail4sub.temp_sale_amount
     * @mbggenerated
     */
    public void setTempSaleAmount(Double tempSaleAmount) {
        this.tempSaleAmount = tempSaleAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4sub.sale_price
     * 
     * @return the value of tbl_order_detail4sub.sale_price
     * @mbggenerated
     */
    public Double getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(Double salePrice) {
        this.salePrice = salePrice;
    }

    public Double getActivePrice() {
        return activePrice;
    }

    public void setActivePrice(Double activePrice) {
        this.activePrice = activePrice;
    }

    /**
     * @mbggenerated
     */
    public Double getPaymentPrefAmount() {
        return paymentPrefAmount;
    }

    /**
     * @mbggenerated
     */
    public void setPaymentPrefAmount(Double paymentPrefAmount) {
        this.paymentPrefAmount = paymentPrefAmount;
    }

    public Double getBuyReductionPrefAmount() {
		return buyReductionPrefAmount;
	}

	public void setBuyReductionPrefAmount(Double buyReductionPrefAmount) {
		this.buyReductionPrefAmount = buyReductionPrefAmount;
	}
	public String getCatNo() {
		return catNo;
	}

	public void setCatNo(String catNo) {
		this.catNo = catNo;
	}
    
}
