package com.yougou.kaidian.order.model;

import java.io.Serializable;
import java.util.Date;

/**
 * @author daixiaowei
 * @date 2012-03-07 10:53:36
 */
public class OrderLog implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_order_log.id
     * 
     * @mbggenerated
     */
    private String  id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_log.behaviout_describe
     * 
     * @mbggenerated
     */
    private String  behavioutDescribe;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_log.create_time
     * 
     * @mbggenerated
     */
    private Date    createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_log.log_type
     * 
     * @mbggenerated
     */
    private Integer logType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_log.operate_result
     * 
     * @mbggenerated
     */
    private Integer operateResult;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_log.operate_user
     * 
     * @mbggenerated
     */
    private String  operateUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_log.order_no
     * 
     * @mbggenerated
     */
    private String  orderNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tbl_order_log.remark
     * 
     * @mbggenerated
     */
    private String  remark;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_log.apply_id
     * 
     * @mbggenerated
     */
    private String  applyId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_log.id
     * 
     * @return the value of tbl_order_log.id
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_log.id
     * 
     * @param id the value for tbl_order_log.id
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_log.behaviout_describe
     * 
     * @return the value of tbl_order_log.behaviout_describe
     * @mbggenerated
     */
    public String getBehavioutDescribe() {
        return behavioutDescribe;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_log.behaviout_describe
     * 
     * @param behavioutDescribe the value for tbl_order_log.behaviout_describe
     * @mbggenerated
     */
    public void setBehavioutDescribe(String behavioutDescribe) {
        this.behavioutDescribe = behavioutDescribe == null ? null : behavioutDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_log.create_time
     * 
     * @return the value of tbl_order_log.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_log.create_time
     * 
     * @param createTime the value for tbl_order_log.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_log.log_type
     * 
     * @return the value of tbl_order_log.log_type
     * @mbggenerated
     */
    public Integer getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_log.log_type
     * 
     * @param logType the value for tbl_order_log.log_type
     * @mbggenerated
     */
    public void setLogType(Integer logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_log.operate_result
     * 
     * @return the value of tbl_order_log.operate_result
     * @mbggenerated
     */
    public Integer getOperateResult() {
        return operateResult;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_log.operate_result
     * 
     * @param operateResult the value for tbl_order_log.operate_result
     * @mbggenerated
     */
    public void setOperateResult(Integer operateResult) {
        this.operateResult = operateResult;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_log.operate_user
     * 
     * @return the value of tbl_order_log.operate_user
     * @mbggenerated
     */
    public String getOperateUser() {
        return operateUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_log.operate_user
     * 
     * @param operateUser the value for tbl_order_log.operate_user
     * @mbggenerated
     */
    public void setOperateUser(String operateUser) {
        this.operateUser = operateUser == null ? null : operateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_log.order_no
     * 
     * @return the value of tbl_order_log.order_no
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_log.order_no
     * 
     * @param orderNo the value for tbl_order_log.order_no
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_log.remark
     * 
     * @return the value of tbl_order_log.remark
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_log.remark
     * 
     * @param remark the value for tbl_order_log.remark
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_log.apply_id
     * 
     * @return the value of tbl_order_log.apply_id
     * @mbggenerated
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_log.apply_id
     * 
     * @param applyId the value for tbl_order_log.apply_id
     * @mbggenerated
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }
}
