package com.yougou.kaidian.order.model;

import java.io.Serializable;

/**
 * @author daixiaowei
 * @date 2012-03-07 10:53:36
 */
public class OrderDetail4main implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.id
     * 
     * @mbggenerated
     */
    private String  id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.order_main_id
     * 
     * @mbggenerated
     */
    private String  orderMainId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.commodity_id
     * 
     * @mbggenerated
     */
    private String  commodityId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.commodity_no
     * 
     * @mbggenerated
     */
    private String  commodityNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.prod_no
     * 
     * @mbggenerated
     */
    private String  prodNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.prod_name
     * 
     * @mbggenerated
     */
    private String  prodName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.prod_type
     * 
     * @mbggenerated
     */
    private String  prodType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.commodity_specification_str
     * 
     * @mbggenerated
     */
    private String  commoditySpecificationStr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.commodity_num
     * 
     * @mbggenerated
     */
    private Integer commodityNum;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.commodity_weight
     * 
     * @mbggenerated
     */
    private Double  commodityWeight;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.prod_total_amt
     * 
     * @mbggenerated
     */
    private Double  prodTotalAmt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.commodity_image
     * 
     * @mbggenerated
     */
    private String  commodityImage;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.split_flag
     * 
     * @mbggenerated
     */
    private Short   splitFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.del_flag
     * 
     * @mbggenerated
     */
    private Short   delFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.main_detail_no
     * 
     * @mbggenerated
     */
    private String  mainDetailNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.prod_unit_price
     * 
     * @mbggenerated
     */
    private Double  prodUnitPrice;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.prod_discount_amount
     * 
     * @mbggenerated
     */
    private Double  prodDiscountAmount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.giving_scores
     * 
     * @mbggenerated
     */
    private Integer givingScores;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * tbl_order_detail4main.commodity_type
     * 
     * @mbggenerated
     */
    private Integer commodityType;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.id
     * 
     * @return the value of tbl_order_detail4main.id
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.id
     * 
     * @param id the value for tbl_order_detail4main.id
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.order_main_id
     * 
     * @return the value of tbl_order_detail4main.order_main_id
     * @mbggenerated
     */
    public String getOrderMainId() {
        return orderMainId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.order_main_id
     * 
     * @param orderMainId the value for tbl_order_detail4main.order_main_id
     * @mbggenerated
     */
    public void setOrderMainId(String orderMainId) {
        this.orderMainId = orderMainId == null ? null : orderMainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.commodity_id
     * 
     * @return the value of tbl_order_detail4main.commodity_id
     * @mbggenerated
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.commodity_id
     * 
     * @param commodityId the value for tbl_order_detail4main.commodity_id
     * @mbggenerated
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.commodity_no
     * 
     * @return the value of tbl_order_detail4main.commodity_no
     * @mbggenerated
     */
    public String getCommodityNo() {
        return commodityNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.commodity_no
     * 
     * @param commodityNo the value for tbl_order_detail4main.commodity_no
     * @mbggenerated
     */
    public void setCommodityNo(String commodityNo) {
        this.commodityNo = commodityNo == null ? null : commodityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.prod_no
     * 
     * @return the value of tbl_order_detail4main.prod_no
     * @mbggenerated
     */
    public String getProdNo() {
        return prodNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.prod_no
     * 
     * @param prodNo the value for tbl_order_detail4main.prod_no
     * @mbggenerated
     */
    public void setProdNo(String prodNo) {
        this.prodNo = prodNo == null ? null : prodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.prod_name
     * 
     * @return the value of tbl_order_detail4main.prod_name
     * @mbggenerated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.prod_name
     * 
     * @param prodName the value for tbl_order_detail4main.prod_name
     * @mbggenerated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.prod_type
     * 
     * @return the value of tbl_order_detail4main.prod_type
     * @mbggenerated
     */
    public String getProdType() {
        return prodType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.prod_type
     * 
     * @param prodType the value for tbl_order_detail4main.prod_type
     * @mbggenerated
     */
    public void setProdType(String prodType) {
        this.prodType = prodType == null ? null : prodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.commodity_specification_str
     * 
     * @return the value of tbl_order_detail4main.commodity_specification_str
     * @mbggenerated
     */
    public String getCommoditySpecificationStr() {
        return commoditySpecificationStr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.commodity_specification_str
     * 
     * @param commoditySpecificationStr the value for tbl_order_detail4main.commodity_specification_str
     * @mbggenerated
     */
    public void setCommoditySpecificationStr(String commoditySpecificationStr) {
        this.commoditySpecificationStr = commoditySpecificationStr == null ? null : commoditySpecificationStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.commodity_num
     * 
     * @return the value of tbl_order_detail4main.commodity_num
     * @mbggenerated
     */
    public Integer getCommodityNum() {
        return commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.commodity_num
     * 
     * @param commodityNum the value for tbl_order_detail4main.commodity_num
     * @mbggenerated
     */
    public void setCommodityNum(Integer commodityNum) {
        this.commodityNum = commodityNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.commodity_weight
     * 
     * @return the value of tbl_order_detail4main.commodity_weight
     * @mbggenerated
     */
    public Double getCommodityWeight() {
        return commodityWeight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.commodity_weight
     * 
     * @param commodityWeight the value for tbl_order_detail4main.commodity_weight
     * @mbggenerated
     */
    public void setCommodityWeight(Double commodityWeight) {
        this.commodityWeight = commodityWeight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.prod_total_amt
     * 
     * @return the value of tbl_order_detail4main.prod_total_amt
     * @mbggenerated
     */
    public Double getProdTotalAmt() {
        return prodTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.prod_total_amt
     * 
     * @param prodTotalAmt the value for tbl_order_detail4main.prod_total_amt
     * @mbggenerated
     */
    public void setProdTotalAmt(Double prodTotalAmt) {
        this.prodTotalAmt = prodTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.commodity_image
     * 
     * @return the value of tbl_order_detail4main.commodity_image
     * @mbggenerated
     */
    public String getCommodityImage() {
        return commodityImage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.commodity_image
     * 
     * @param commodityImage the value for tbl_order_detail4main.commodity_image
     * @mbggenerated
     */
    public void setCommodityImage(String commodityImage) {
        this.commodityImage = commodityImage == null ? null : commodityImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.split_flag
     * 
     * @return the value of tbl_order_detail4main.split_flag
     * @mbggenerated
     */
    public Short getSplitFlag() {
        return splitFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.split_flag
     * 
     * @param splitFlag the value for tbl_order_detail4main.split_flag
     * @mbggenerated
     */
    public void setSplitFlag(Short splitFlag) {
        this.splitFlag = splitFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.del_flag
     * 
     * @return the value of tbl_order_detail4main.del_flag
     * @mbggenerated
     */
    public Short getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.del_flag
     * 
     * @param delFlag the value for tbl_order_detail4main.del_flag
     * @mbggenerated
     */
    public void setDelFlag(Short delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.main_detail_no
     * 
     * @return the value of tbl_order_detail4main.main_detail_no
     * @mbggenerated
     */
    public String getMainDetailNo() {
        return mainDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.main_detail_no
     * 
     * @param mainDetailNo the value for tbl_order_detail4main.main_detail_no
     * @mbggenerated
     */
    public void setMainDetailNo(String mainDetailNo) {
        this.mainDetailNo = mainDetailNo == null ? null : mainDetailNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.prod_unit_price
     * 
     * @return the value of tbl_order_detail4main.prod_unit_price
     * @mbggenerated
     */
    public Double getProdUnitPrice() {
        return prodUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.prod_unit_price
     * 
     * @param prodUnitPrice the value for tbl_order_detail4main.prod_unit_price
     * @mbggenerated
     */
    public void setProdUnitPrice(Double prodUnitPrice) {
        this.prodUnitPrice = prodUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.prod_discount_amount
     * 
     * @return the value of tbl_order_detail4main.prod_discount_amount
     * @mbggenerated
     */
    public Double getProdDiscountAmount() {
        return prodDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.prod_discount_amount
     * 
     * @param prodDiscountAmount the value for tbl_order_detail4main.prod_discount_amount
     * @mbggenerated
     */
    public void setProdDiscountAmount(Double prodDiscountAmount) {
        this.prodDiscountAmount = prodDiscountAmount;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.giving_scores
     * 
     * @return the value of tbl_order_detail4main.giving_scores
     * @mbggenerated
     */
    public Integer getGivingScores() {
        return givingScores;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.giving_scores
     * 
     * @param givingScores the value for tbl_order_detail4main.giving_scores
     * @mbggenerated
     */
    public void setGivingScores(Integer givingScores) {
        this.givingScores = givingScores;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * tbl_order_detail4main.commodity_type
     * 
     * @return the value of tbl_order_detail4main.commodity_type
     * @mbggenerated
     */
    public Integer getCommodityType() {
        return commodityType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * tbl_order_detail4main.commodity_type
     * 
     * @param commodityType the value for tbl_order_detail4main.commodity_type
     * @mbggenerated
     */
    public void setCommodityType(Integer commodityType) {
        this.commodityType = commodityType;
    }
}
