package com.yougou.kaidian.order.model;

import java.math.BigDecimal;

public class OtherOutStoreDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.commodity_id
     *
     * @mbggenerated
     */
    private String commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.commodity_code
     *
     * @mbggenerated
     */
    private String commodityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.origin_code
     *
     * @mbggenerated
     */
    private String originCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.specification
     *
     * @mbggenerated
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.units
     *
     * @mbggenerated
     */
    private String units;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.unit_price
     *
     * @mbggenerated
     */
    private BigDecimal unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.total_price
     *
     * @mbggenerated
     */
    private BigDecimal totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.other_out_store_id
     *
     * @mbggenerated
     */
    private String otherOutStoreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.apportion_quantity
     *
     * @mbggenerated
     */
    private Integer apportionQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.receive_quantity
     *
     * @mbggenerated
     */
    private Integer receiveQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_wms_other_out_store_detail.defective_quantity
     *
     * @mbggenerated
     */
    private Integer defectiveQuantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.id
     *
     * @return the value of tbl_wms_other_out_store_detail.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.id
     *
     * @param id the value for tbl_wms_other_out_store_detail.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.commodity_id
     *
     * @return the value of tbl_wms_other_out_store_detail.commodity_id
     *
     * @mbggenerated
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.commodity_id
     *
     * @param commodityId the value for tbl_wms_other_out_store_detail.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId == null ? null : commodityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.commodity_code
     *
     * @return the value of tbl_wms_other_out_store_detail.commodity_code
     *
     * @mbggenerated
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.commodity_code
     *
     * @param commodityCode the value for tbl_wms_other_out_store_detail.commodity_code
     *
     * @mbggenerated
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.origin_code
     *
     * @return the value of tbl_wms_other_out_store_detail.origin_code
     *
     * @mbggenerated
     */
    public String getOriginCode() {
        return originCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.origin_code
     *
     * @param originCode the value for tbl_wms_other_out_store_detail.origin_code
     *
     * @mbggenerated
     */
    public void setOriginCode(String originCode) {
        this.originCode = originCode == null ? null : originCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.goods_name
     *
     * @return the value of tbl_wms_other_out_store_detail.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.goods_name
     *
     * @param goodsName the value for tbl_wms_other_out_store_detail.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.specification
     *
     * @return the value of tbl_wms_other_out_store_detail.specification
     *
     * @mbggenerated
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.specification
     *
     * @param specification the value for tbl_wms_other_out_store_detail.specification
     *
     * @mbggenerated
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.units
     *
     * @return the value of tbl_wms_other_out_store_detail.units
     *
     * @mbggenerated
     */
    public String getUnits() {
        return units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.units
     *
     * @param units the value for tbl_wms_other_out_store_detail.units
     *
     * @mbggenerated
     */
    public void setUnits(String units) {
        this.units = units == null ? null : units.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.unit_price
     *
     * @return the value of tbl_wms_other_out_store_detail.unit_price
     *
     * @mbggenerated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.unit_price
     *
     * @param unitPrice the value for tbl_wms_other_out_store_detail.unit_price
     *
     * @mbggenerated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.quantity
     *
     * @return the value of tbl_wms_other_out_store_detail.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.quantity
     *
     * @param quantity the value for tbl_wms_other_out_store_detail.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.total_price
     *
     * @return the value of tbl_wms_other_out_store_detail.total_price
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.total_price
     *
     * @param totalPrice the value for tbl_wms_other_out_store_detail.total_price
     *
     * @mbggenerated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.other_out_store_id
     *
     * @return the value of tbl_wms_other_out_store_detail.other_out_store_id
     *
     * @mbggenerated
     */
    public String getOtherOutStoreId() {
        return otherOutStoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.other_out_store_id
     *
     * @param otherOutStoreId the value for tbl_wms_other_out_store_detail.other_out_store_id
     *
     * @mbggenerated
     */
    public void setOtherOutStoreId(String otherOutStoreId) {
        this.otherOutStoreId = otherOutStoreId == null ? null : otherOutStoreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.status
     *
     * @return the value of tbl_wms_other_out_store_detail.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.status
     *
     * @param status the value for tbl_wms_other_out_store_detail.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.apportion_quantity
     *
     * @return the value of tbl_wms_other_out_store_detail.apportion_quantity
     *
     * @mbggenerated
     */
    public Integer getApportionQuantity() {
        return apportionQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.apportion_quantity
     *
     * @param apportionQuantity the value for tbl_wms_other_out_store_detail.apportion_quantity
     *
     * @mbggenerated
     */
    public void setApportionQuantity(Integer apportionQuantity) {
        this.apportionQuantity = apportionQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.receive_quantity
     *
     * @return the value of tbl_wms_other_out_store_detail.receive_quantity
     *
     * @mbggenerated
     */
    public Integer getReceiveQuantity() {
        return receiveQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.receive_quantity
     *
     * @param receiveQuantity the value for tbl_wms_other_out_store_detail.receive_quantity
     *
     * @mbggenerated
     */
    public void setReceiveQuantity(Integer receiveQuantity) {
        this.receiveQuantity = receiveQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_wms_other_out_store_detail.defective_quantity
     *
     * @return the value of tbl_wms_other_out_store_detail.defective_quantity
     *
     * @mbggenerated
     */
    public Integer getDefectiveQuantity() {
        return defectiveQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_wms_other_out_store_detail.defective_quantity
     *
     * @param defectiveQuantity the value for tbl_wms_other_out_store_detail.defective_quantity
     *
     * @mbggenerated
     */
    public void setDefectiveQuantity(Integer defectiveQuantity) {
        this.defectiveQuantity = defectiveQuantity;
    }
}